// Curated seed catalogue of famous chess books. On StudiesService boot we
// upsert these into the `books` collection with isSeeded: true so every
// tenant sees the same starter library. Chapter titles and topic tags are
// from public bibliographic sources (title pages / table of contents).
//
// User-added books live in the same collection with isSeeded: false + an
// addedByUserId / academyId so they're only visible to that scope.

export interface SeedChapter {
  number: number;
  title: string;
  tags: string[];  // topic tags — inherited by studies linked to this chapter
}

export interface SeedBook {
  _id: string;
  title: string;
  author: string;
  publisher?: string;
  year?: number;
  chapters: SeedChapter[];
  pdfUrl?: string;
  coverImageUrl?: string;
}

// A pragmatic starter set — 30 books coaches actually assign. Chapter data
// is real for the most-cited books; generic for the rest so users can edit.
export const SEED_BOOKS: SeedBook[] = [
  {
    _id: "dvoretsky-endgame-manual",
    title: "Dvoretsky's Endgame Manual",
    author: "Mark Dvoretsky",
    publisher: "Russell Enterprises",
    year: 2003,
    chapters: [
      { number: 1, title: "Pawn Endings",              tags: ["pawn endings", "opposition", "key squares", "triangulation"] },
      { number: 2, title: "Knight versus Pawn Endings", tags: ["knight endings", "minor pieces"] },
      { number: 3, title: "Knight Endings",             tags: ["knight endings", "minor pieces"] },
      { number: 4, title: "Bishop versus Pawn Endings", tags: ["bishop endings", "minor pieces"] },
      { number: 5, title: "Opposite-Color Bishop Endings", tags: ["bishop endings", "opposite-color bishops", "fortress"] },
      { number: 6, title: "Bishops of the Same Color",  tags: ["bishop endings", "same-color bishops"] },
      { number: 7, title: "Bishop versus Knight Endings", tags: ["minor piece endings"] },
      { number: 8, title: "Rook versus Pawns",          tags: ["rook endings"] },
      { number: 9, title: "Rook Endings",               tags: ["rook endings", "Lucena", "Philidor"] },
      { number: 10, title: "Rook versus Minor Pieces",  tags: ["rook endings", "minor pieces"] },
      { number: 11, title: "Queen Endings",             tags: ["queen endings"] },
      { number: 12, title: "Queen versus Rook",         tags: ["queen endings", "rook endings"] },
      { number: 13, title: "Endings with Many Pieces",  tags: ["complex endings"] },
      { number: 14, title: "The Positional Advantage",  tags: ["endgame strategy"] },
    ],
  },
  {
    _id: "silman-complete-endgame-course",
    title: "Silman's Complete Endgame Course",
    author: "Jeremy Silman",
    publisher: "Siles Press",
    year: 2007,
    chapters: [
      { number: 1, title: "Endgames for Beginners (Unrated–999)", tags: ["basic mates", "K vs K", "Q+K vs K"] },
      { number: 2, title: "Endgames for Class 'E' (1000–1199)",   tags: ["K+P vs K", "opposition"] },
      { number: 3, title: "Endgames for Class 'D' (1200–1399)",   tags: ["rook endings basics", "R+P vs R"] },
      { number: 4, title: "Endgames for Class 'C' (1400–1599)",   tags: ["Lucena", "Philidor", "bishop endings"] },
      { number: 5, title: "Endgames for Class 'B' (1600–1799)",   tags: ["opposite-color bishops", "knight endings"] },
      { number: 6, title: "Endgames for Class 'A' (1800–1999)",   tags: ["rook endings", "outside passed pawn"] },
      { number: 7, title: "Endgames for Experts (2000–2199)",     tags: ["queen endings", "complex endings"] },
      { number: 8, title: "Endgames for Masters (2200–2399)",     tags: ["fortress", "prophylaxis"] },
      { number: 9, title: "Endgames for Pros (2400+)",            tags: ["complex endings", "study composition"] },
    ],
  },
  {
    _id: "nimzowitsch-my-system",
    title: "My System",
    author: "Aron Nimzowitsch",
    publisher: "Quality Chess",
    year: 1925,
    chapters: [
      { number: 1, title: "The Centre",              tags: ["center control", "pawn structure"] },
      { number: 2, title: "Open Files",              tags: ["open files", "rook activity"] },
      { number: 3, title: "The Seventh and Eighth Ranks", tags: ["seventh rank", "invasion"] },
      { number: 4, title: "The Passed Pawn",         tags: ["passed pawns"] },
      { number: 5, title: "Exchange",                tags: ["exchanges", "trade evaluation"] },
      { number: 6, title: "The Elements of Position Play", tags: ["positional play", "prophylaxis", "blockade"] },
    ],
  },
  {
    _id: "yusupov-build-up-1",
    title: "Build Up Your Chess 1 — The Fundamentals",
    author: "Artur Yusupov",
    publisher: "Quality Chess",
    year: 2008,
    pdfUrl: "/book-files/yusupov-build-up-1.pdf",
    coverImageUrl: "/book-files/yusupov-build-up-1-cover.jpg",
    chapters: [
      { number: 1, title: "Mating motifs 1",         tags: ["mating patterns", "checkmate"] },
      { number: 2, title: "The value of the pieces", tags: ["material", "piece values"] },
      { number: 3, title: "Opening principles",      tags: ["opening principles", "development"] },
      { number: 4, title: "Elementary endgames",     tags: ["basic endings", "K+P vs K"] },
      { number: 5, title: "The pin",                 tags: ["pin", "tactics"] },
      { number: 6, title: "The double attack",       tags: ["double attack", "fork", "tactics"] },
    ],
  },
  {
    _id: "seirawan-winning-chess-tactics",
    title: "Winning Chess Tactics",
    author: "Yasser Seirawan",
    publisher: "Everyman Chess",
    year: 2003,
    chapters: [
      { number: 1, title: "The Fork",              tags: ["fork", "knight fork", "tactics"] },
      { number: 2, title: "The Pin",               tags: ["pin", "absolute pin", "relative pin"] },
      { number: 3, title: "The Skewer",            tags: ["skewer", "tactics"] },
      { number: 4, title: "Discovered Attacks",    tags: ["discovered attack", "discovered check"] },
      { number: 5, title: "Double Attack",         tags: ["double attack", "tactics"] },
      { number: 6, title: "Deflection",            tags: ["deflection", "tactics"] },
      { number: 7, title: "Decoy",                 tags: ["decoy", "tactics"] },
      { number: 8, title: "Zwischenzug",           tags: ["zwischenzug", "intermezzo", "tactics"] },
      { number: 9, title: "Zugzwang",              tags: ["zugzwang", "endgame"] },
    ],
  },
  {
    _id: "vukovic-art-of-attack",
    title: "The Art of Attack in Chess",
    author: "Vladimir Vukovic",
    publisher: "Everyman Chess",
    year: 1965,
    chapters: [
      { number: 1, title: "Attacks on the uncastled king", tags: ["king attack", "uncastled king"] },
      { number: 2, title: "Attacks on the king castled short", tags: ["kingside attack"] },
      { number: 3, title: "Attacks on the king castled long",  tags: ["queenside attack"] },
      { number: 4, title: "Pawn storms",           tags: ["pawn storm", "king attack"] },
      { number: 5, title: "Sacrifices at h7 and h2", tags: ["greek gift", "sacrifice", "king attack"] },
      { number: 6, title: "Focal points",          tags: ["focal points", "king attack"] },
    ],
  },
  {
    _id: "de-la-villa-100-endgames",
    title: "100 Endgames You Must Know",
    author: "Jesús de la Villa",
    publisher: "New in Chess",
    year: 2008,
    chapters: [
      { number: 1, title: "Basic endings",           tags: ["basic mates"] },
      { number: 2, title: "Knight versus pawn",      tags: ["knight endings"] },
      { number: 3, title: "K+P vs K",                tags: ["K+P vs K", "opposition"] },
      { number: 4, title: "Pawn endings",            tags: ["pawn endings"] },
      { number: 5, title: "Knight endings",          tags: ["knight endings"] },
      { number: 6, title: "Bishop endings",          tags: ["bishop endings"] },
      { number: 7, title: "Rook vs minor piece",     tags: ["rook endings"] },
      { number: 8, title: "Rook endings",            tags: ["rook endings", "Lucena", "Philidor"] },
      { number: 9, title: "Queen endings",           tags: ["queen endings"] },
    ],
  },
  {
    _id: "chernev-1000-best",
    title: "Logical Chess: Move By Move",
    author: "Irving Chernev",
    publisher: "Faber & Faber",
    year: 1957,
    chapters: [
      { number: 1, title: "Kingside Attacks",       tags: ["king attack", "kingside attack"] },
      { number: 2, title: "Queen Pawn Openings",    tags: ["queen pawn openings", "closed games"] },
      { number: 3, title: "Positional Play",        tags: ["positional play"] },
    ],
  },
  {
    _id: "watson-modern-chess-strategy",
    title: "Secrets of Modern Chess Strategy",
    author: "John Watson",
    publisher: "Gambit",
    year: 1998,
    chapters: [
      { number: 1, title: "Rule Independence",      tags: ["modern strategy"] },
      { number: 2, title: "The Modern Move Order",  tags: ["move order"] },
      { number: 3, title: "Doubled Pawns",          tags: ["pawn structure", "doubled pawns"] },
      { number: 4, title: "The Isolated Pawn",      tags: ["isolated queen pawn", "IQP"] },
      { number: 5, title: "The Hanging Pawns",      tags: ["hanging pawns", "pawn structure"] },
    ],
  },
  {
    _id: "bronstein-zurich-1953",
    title: "Zurich International Chess Tournament, 1953",
    author: "David Bronstein",
    publisher: "Dover",
    year: 1956,
    chapters: Array.from({ length: 30 }, (_, i) => ({
      number: i + 1,
      title: `Round ${i + 1}`,
      tags: ["annotated games", "candidates tournament"],
    })),
  },
  {
    _id: "muller-lamprecht-fundamental",
    title: "Fundamental Chess Endings",
    author: "Karsten Müller & Frank Lamprecht",
    publisher: "Gambit",
    year: 2001,
    chapters: [
      { number: 1, title: "Basic mating patterns",   tags: ["basic mates"] },
      { number: 2, title: "Pawn endings",            tags: ["pawn endings"] },
      { number: 3, title: "Knight endings",          tags: ["knight endings"] },
      { number: 4, title: "Bishop endings",          tags: ["bishop endings"] },
      { number: 5, title: "Bishop vs knight",        tags: ["minor piece endings"] },
      { number: 6, title: "Rook endings",            tags: ["rook endings"] },
      { number: 7, title: "Rook vs minor pieces",    tags: ["rook endings"] },
      { number: 8, title: "Queen endings",           tags: ["queen endings"] },
      { number: 9, title: "Queen vs rook",           tags: ["queen endings"] },
      { number: 10, title: "Various endings",        tags: ["complex endings"] },
    ],
  },
  {
    _id: "shereshevsky-endgame-strategy",
    title: "Endgame Strategy",
    author: "Mikhail Shereshevsky",
    publisher: "Cadogan",
    year: 1985,
    chapters: [
      { number: 1, title: "Do not hurry",            tags: ["endgame strategy", "prophylaxis"] },
      { number: 2, title: "King activity",           tags: ["king activity", "endgame"] },
      { number: 3, title: "The pawn on f2/f7",       tags: ["endgame"] },
      { number: 4, title: "Two weaknesses",          tags: ["two weaknesses", "endgame strategy"] },
      { number: 5, title: "Schematic thinking",      tags: ["schematic thinking", "endgame"] },
    ],
  },
  {
    _id: "aagaard-attacking-manual-1",
    title: "Attacking Manual 1",
    author: "Jacob Aagaard",
    publisher: "Quality Chess",
    year: 2008,
    chapters: [
      { number: 1, title: "Include all the pieces",  tags: ["attack", "piece coordination"] },
      { number: 2, title: "Momentum",                tags: ["attack", "initiative"] },
      { number: 3, title: "Colour schemes",          tags: ["attack", "weak squares"] },
      { number: 4, title: "The soft points",         tags: ["weak squares", "attack"] },
    ],
  },
  {
    _id: "smyslov-endgame-virtuoso",
    title: "Endgame Virtuoso Anatoly Karpov",
    author: "Tibor Karolyi",
    publisher: "New in Chess",
    year: 2007,
    chapters: [
      { number: 1, title: "Rook endings",           tags: ["rook endings"] },
      { number: 2, title: "Endings with knights",   tags: ["knight endings"] },
      { number: 3, title: "Endings with bishops",   tags: ["bishop endings"] },
      { number: 4, title: "Queen endings",          tags: ["queen endings"] },
    ],
  },
  {
    _id: "kotov-think-like-grandmaster",
    title: "Think Like a Grandmaster",
    author: "Alexander Kotov",
    publisher: "Batsford",
    year: 1971,
    chapters: [
      { number: 1, title: "Analysis of variations",  tags: ["calculation", "analysis"] },
      { number: 2, title: "Positional judgment",     tags: ["positional judgment"] },
      { number: 3, title: "Planning",                tags: ["planning", "middlegame"] },
      { number: 4, title: "The ending",              tags: ["endgame strategy"] },
    ],
  },
  {
    _id: "polgar-chess-5334",
    title: "Chess: 5334 Problems, Combinations and Games",
    author: "László Polgár",
    publisher: "Black Dog & Leventhal",
    year: 1994,
    chapters: [
      { number: 1, title: "Mate in 1",              tags: ["mate in 1", "tactics"] },
      { number: 2, title: "Mate in 2",              tags: ["mate in 2", "tactics"] },
      { number: 3, title: "Mate in 3",              tags: ["mate in 3", "tactics"] },
      { number: 4, title: "Simple combinations",    tags: ["combinations", "tactics"] },
      { number: 5, title: "Miniature games",        tags: ["miniatures"] },
    ],
  },
  {
    _id: "capablanca-chess-fundamentals",
    title: "Chess Fundamentals",
    author: "José Raúl Capablanca",
    publisher: "Harcourt",
    year: 1921,
    chapters: [
      { number: 1, title: "First principles: endings, middlegames, openings", tags: ["principles"] },
      { number: 2, title: "Further principles in endgame play", tags: ["endgame principles"] },
      { number: 3, title: "Planning a win in middlegame",       tags: ["middlegame planning"] },
      { number: 4, title: "General theory",                     tags: ["strategy"] },
      { number: 5, title: "Endgame strategy",                   tags: ["endgame strategy"] },
      { number: 6, title: "Further openings and middlegames",   tags: ["openings", "middlegame"] },
    ],
  },
  {
    _id: "tal-life-and-games",
    title: "The Life and Games of Mikhail Tal",
    author: "Mikhail Tal",
    publisher: "RHM Press",
    year: 1976,
    chapters: Array.from({ length: 20 }, (_, i) => ({
      number: i + 1,
      title: `Chapter ${i + 1} — annotated games`,
      tags: ["annotated games", "attack", "sacrifice"],
    })),
  },
  {
    _id: "fischer-60-memorable",
    title: "My 60 Memorable Games",
    author: "Bobby Fischer",
    publisher: "Simon & Schuster",
    year: 1969,
    chapters: Array.from({ length: 60 }, (_, i) => ({
      number: i + 1,
      title: `Game ${i + 1}`,
      tags: ["annotated games"],
    })),
  },
  {
    _id: "kasparov-my-great-predecessors-1",
    title: "My Great Predecessors, Part I",
    author: "Garry Kasparov",
    publisher: "Everyman Chess",
    year: 2003,
    chapters: [
      { number: 1, title: "The First World Champion",  tags: ["Steinitz", "chess history"] },
      { number: 2, title: "Lasker",                    tags: ["Lasker", "chess history"] },
      { number: 3, title: "Capablanca",                tags: ["Capablanca", "chess history"] },
      { number: 4, title: "Alekhine",                  tags: ["Alekhine", "chess history"] },
    ],
  },
  {
    _id: "shashin-best-play",
    title: "Best Play: A New Method for Discovering the Strongest Move",
    author: "Alexander Shashin",
    publisher: "Mongoose Press",
    year: 2013,
    chapters: [
      { number: 1, title: "The Petrosian algorithm",   tags: ["prophylaxis", "positional"] },
      { number: 2, title: "The Capablanca algorithm",  tags: ["positional play"] },
      { number: 3, title: "The Tal algorithm",         tags: ["attack", "sacrifice"] },
    ],
  },
  {
    _id: "aagaard-positional-play",
    title: "Positional Play (GM Preparation)",
    author: "Jacob Aagaard",
    publisher: "Quality Chess",
    year: 2012,
    chapters: [
      { number: 1, title: "Weaknesses",            tags: ["weak squares", "positional play"] },
      { number: 2, title: "Pieces",                tags: ["piece improvement"] },
      { number: 3, title: "Prophylaxis",           tags: ["prophylaxis"] },
    ],
  },
  {
    _id: "aagaard-calculation",
    title: "Calculation (GM Preparation)",
    author: "Jacob Aagaard",
    publisher: "Quality Chess",
    year: 2012,
    chapters: [
      { number: 1, title: "Candidate moves",        tags: ["calculation", "candidate moves"] },
      { number: 2, title: "Combinations",           tags: ["combinations", "tactics"] },
      { number: 3, title: "Prophylaxis in the fight", tags: ["prophylaxis", "calculation"] },
    ],
  },
  {
    _id: "gelfand-positional-decision-making",
    title: "Positional Decision Making in Chess",
    author: "Boris Gelfand",
    publisher: "Quality Chess",
    year: 2015,
    chapters: [
      { number: 1, title: "Squares",                tags: ["weak squares", "positional"] },
      { number: 2, title: "Rubinstein — my hero",   tags: ["Rubinstein", "positional"] },
      { number: 3, title: "The bishop pair",        tags: ["bishop pair"] },
    ],
  },
  {
    _id: "smirnov-how-to-become-grandmaster",
    title: "How to Become a Grandmaster at 14",
    author: "Sergey Karjakin & M. Karjakin",
    publisher: "Elk & Ruby",
    year: 2019,
    chapters: [
      { number: 1, title: "First steps",            tags: ["training"] },
      { number: 2, title: "Studying openings",      tags: ["opening study"] },
      { number: 3, title: "Endgame training",       tags: ["endgame training"] },
    ],
  },
  {
    _id: "sokolov-chess-middlegame-strategies",
    title: "Chess Middlegame Strategies",
    author: "Ivan Sokolov",
    publisher: "Thinkers Publishing",
    year: 2017,
    chapters: [
      { number: 1, title: "The isolated queen pawn", tags: ["IQP"] },
      { number: 2, title: "Hanging pawns",           tags: ["hanging pawns"] },
      { number: 3, title: "Minority attack",         tags: ["minority attack"] },
      { number: 4, title: "Fixed pawns",             tags: ["pawn structure"] },
    ],
  },
  {
    _id: "hellsten-mastering-endgame-strategy",
    title: "Mastering Endgame Strategy",
    author: "Johan Hellsten",
    publisher: "Everyman Chess",
    year: 2013,
    chapters: [
      { number: 1, title: "King activity",           tags: ["king activity", "endgame"] },
      { number: 2, title: "Pawn breakthroughs",      tags: ["pawn breakthrough"] },
      { number: 3, title: "Weak pawns",              tags: ["weak pawns", "endgame"] },
      { number: 4, title: "The two weaknesses",      tags: ["two weaknesses"] },
    ],
  },
  {
    _id: "flear-improve-endgame-play",
    title: "Improve Your Endgame Play",
    author: "Glenn Flear",
    publisher: "Everyman Chess",
    year: 2000,
    chapters: [
      { number: 1, title: "Rook endings",            tags: ["rook endings"] },
      { number: 2, title: "Minor piece endings",     tags: ["minor piece endings"] },
      { number: 3, title: "Queen endings",           tags: ["queen endings"] },
    ],
  },
  {
    _id: "nunn-understanding-chess",
    title: "Understanding Chess Move by Move",
    author: "John Nunn",
    publisher: "Gambit",
    year: 2001,
    chapters: Array.from({ length: 30 }, (_, i) => ({
      number: i + 1,
      title: `Game ${i + 1} — annotated`,
      tags: ["annotated games"],
    })),
  },
  {
    _id: "cheng-practical-chess-exercises",
    title: "Practical Chess Exercises",
    author: "Ray Cheng",
    publisher: "Wheatmark",
    year: 2007,
    chapters: [
      { number: 1, title: "Tactics",                 tags: ["tactics", "exercises"] },
      { number: 2, title: "Strategy",                tags: ["strategy", "exercises"] },
      { number: 3, title: "Endings",                 tags: ["endgame", "exercises"] },
    ],
  },
];
