// Memory Palace — the 64-square memory system (Set 1: Classic Animals & Objects).
// Each square is assigned a vivid, funny scene built from two mnemonics:
//   • file letter (a–h) → a word starting with that letter   (a = Ant, b = Bear …)
//   • rank number (1–8) → a word that RHYMES with the number  (1 = Sun, 2 = Shoe …)
// So a1 = "Ant + Sun", h8 = "Hedgehog + Ate". The bizarre image makes the
// coordinate impossible to forget (memory-champions' "bizarreness effect").
// Source: chess_memory_system.md (built for Harinitha's chess journey).

export interface Scene {
  pair: string;   // e.g. "Ant + Sun"
  emoji: string;  // kid-friendly visual anchor
  scene: string;  // the vivid one-line story for this square
}

// Files → alliterative animal/word per square.  Ranks → rhyming object.
// Indexed [square] e.g. SCENES["a1"].

const SET1: Record<string, Scene> = {
  // Rank 1 — rhymes with ONE (Sun/Bun/Fun/Run/One/Nun/Gun/Swan)
  a1: { pair: "Ant + Sun",       emoji: "🐜", scene: "A tiny ant in sunglasses tans on the Sun, sipping lemonade. “This tanning bed is HOT!”" },
  b1: { pair: "Bear + Bun",      emoji: "🐻", scene: "A huge bear sits on a giant burger Bun like a throne, napkin tucked in. “I am King of the Bun!”" },
  c1: { pair: "Cat + Fun",       emoji: "🐱", scene: "A cat having the most Fun ever at a party — confetti flying everywhere." },
  d1: { pair: "Dog + Run",       emoji: "🐶", scene: "A dog on a Run, racing so fast its ears flap like wings." },
  e1: { pair: "Elephant + One",  emoji: "🐘", scene: "An elephant balances on One toe like a ballerina, wearing a tutu. “Tada!”" },
  f1: { pair: "Fox + Nun",       emoji: "🦊", scene: "A sly fox dressed as a Nun, tiptoeing out of the kitchen." },
  g1: { pair: "Goat + Gun",      emoji: "🐐", scene: "A goat runs wild with a water Gun, soaking everyone. Maniacal grin." },
  h1: { pair: "Horse + Swan",    emoji: "🐴", scene: "A horse in a Swan costume at a ballet recital — it falls, gracefully." },
  // Rank 2 — rhymes with TWO / Shoe (Zoo/Glue/Stew/Moo/Crew/Chew/Blue/Shoe)
  a2: { pair: "Aeroplane + Zoo", emoji: "✈️", scene: "A paper Aeroplane flies the whole Zoo on a field trip across the sky." },
  b2: { pair: "Banana + Glue",   emoji: "🍌", scene: "A Banana stuck to the floor with Glue — nobody can peel it free." },
  c2: { pair: "Clown + Stew",    emoji: "🤡", scene: "A Clown cooks a bubbling Stew, juggling carrots into the pot." },
  d2: { pair: "Duck + Moo",      emoji: "🦆", scene: "A Duck that forgot how to quack and goes “Moo!” instead." },
  e2: { pair: "Egg + Crew",      emoji: "🥚", scene: "An Egg captain leads a Crew of tiny eggs sailing a kitchen ship." },
  f2: { pair: "Frog + Chew",     emoji: "🐸", scene: "A Frog happily Chews the biggest piece of bubblegum ever." },
  g2: { pair: "Giant + Blue",    emoji: "🧍", scene: "A Giant painted all Blue hides in the sky, pretending to be a cloud." },
  h2: { pair: "Hippo + Shoe",    emoji: "🦛", scene: "A Hippo squeezing into one tiny Shoe — it does not fit at all." },
  // Rank 3 — rhymes with THREE / Tree (Tree/Bee/Key/Sea/Tea/Flea/Ski/Knee)
  a3: { pair: "Angel + Tree",    emoji: "👼", scene: "An Angel perched in a Tree, handing out apples to the birds." },
  b3: { pair: "Butterfly + Bee", emoji: "🦋", scene: "A Butterfly and a Bee racing flower to flower." },
  c3: { pair: "Cuckoo + Key",    emoji: "🐦", scene: "A Cuckoo bird pops out of the clock holding a golden Key." },
  d3: { pair: "Dinosaur + Sea",  emoji: "🦕", scene: "A Dinosaur splashing in the Sea with a snorkel and floaties." },
  e3: { pair: "Eagle + Tea",     emoji: "🦅", scene: "An Eagle sips Tea on a mountain top, pinky feather out." },
  f3: { pair: "Firefly + Flea",  emoji: "✨", scene: "A Firefly and a tiny Flea throw a glowing dance party." },
  g3: { pair: "Gorilla + Ski",   emoji: "🦍", scene: "A Gorilla on Skis zooms down a snowy hill, banana in hand." },
  h3: { pair: "Hawk + Knee",     emoji: "🦅", scene: "A Hawk scraped its Knee and wears a little bandage." },
  // Rank 4 — rhymes with FOUR / Door (Door/Floor/Snore/Roar/More/Store/Pour/Boar)
  a4: { pair: "Alien + Door",    emoji: "👽", scene: "An Alien knocks on a Door, asking to borrow some sugar." },
  b4: { pair: "Butler + Floor",  emoji: "🤵", scene: "A Butler polishes the Floor so shiny he skates right across it." },
  c4: { pair: "Captain + Snore", emoji: "⚓", scene: "A ship Captain Snores so loud the sails puff out." },
  d4: { pair: "Doctor + Roar",   emoji: "🩺", scene: "A Doctor with a stethoscope Roars like a lion. The patient faints." },
  e4: { pair: "Emperor + More",  emoji: "👑", scene: "An Emperor shouts “More cake!” at a giant feast." },
  f4: { pair: "Farmer + Store",  emoji: "👨‍🌾", scene: "A Farmer opens a Store that only sells giant vegetables." },
  g4: { pair: "Gardener + Pour", emoji: "🌱", scene: "A Gardener Pours water from a little cloud onto happy flowers." },
  h4: { pair: "Hunter + Boar",   emoji: "🏹", scene: "A Hunter is chased by a friendly Boar that just wants a hug." },
  // Rank 5 — rhymes with FIVE / Hive (Hive/Dive/Five/Drive/Alive/Jive/Thrive/Chive)
  a5: { pair: "Acrobat + Hive",  emoji: "🤸", scene: "An Acrobat does flips around a buzzing bee Hive." },
  b5: { pair: "Bee + Dive",      emoji: "🐝", scene: "A Bee in a swimsuit does a perfect Dive into the honey. 10/10!" },
  c5: { pair: "Crab + Five",     emoji: "🦀", scene: "A Crab gives high-Fives with both claws — fish get launched." },
  d5: { pair: "Drum + Drive",    emoji: "🥁", scene: "A Drum rolls along on a Drive, beating its own rhythm." },
  e5: { pair: "Eskimo + Alive",  emoji: "🧊", scene: "An Eskimo's snowman comes Alive and asks for a warm scarf." },
  f5: { pair: "Flamingo + Jive", emoji: "🦩", scene: "A Flamingo dances the Jive balanced on one pink leg." },
  g5: { pair: "Grasshopper + Thrive", emoji: "🦗", scene: "A Grasshopper's garden Thrives as it hops about watering it." },
  h5: { pair: "Hen + Chive",     emoji: "🐔", scene: "A Hen tends neat rows of Chives, clucking proudly." },
  // Rank 6 — rhymes with SIX / Sticks (Sticks/Bricks/Chicks/Kicks/Fix/Tricks/Mix/Licks)
  a6: { pair: "Alligator + Sticks", emoji: "🐊", scene: "An Alligator builds a fort out of Sticks." },
  b6: { pair: "Broomstick + Bricks", emoji: "🧹", scene: "A Broomstick sweeps a tower of Bricks into a castle." },
  c6: { pair: "Carpenter + Chicks", emoji: "🔨", scene: "A Carpenter builds tiny houses for fluffy Chicks." },
  d6: { pair: "Dancer + Kicks",  emoji: "💃", scene: "A Dancer does high Kicks that reach the ceiling." },
  e6: { pair: "Engineer + Fix",  emoji: "🔧", scene: "An Engineer tries to Fix a robot that keeps hiccuping." },
  f6: { pair: "Fisherman + Tricks", emoji: "🎣", scene: "A Fisherman teaches a fish silly Tricks." },
  g6: { pair: "Ghost + Mix",     emoji: "👻", scene: "A Ghost bakes, Mixing a bowl that floats in mid-air." },
  h6: { pair: "Helicopter + Licks", emoji: "🚁", scene: "A Helicopter with a tongue gives the clouds Licks." },
  // Rank 7 — rhymes with SEVEN / Heaven (Heaven/Eleven/Leaven/7-Heads/Heaven/7-Seas/7-Dwarfs/7th-Sky)
  a7: { pair: "Astronaut + Heaven", emoji: "👨‍🚀", scene: "An Astronaut floats up in Heaven, bouncing from cloud to cloud." },
  b7: { pair: "Bird + Eleven",   emoji: "🐦", scene: "A Bird lays exactly Eleven eggs and counts them proudly." },
  c7: { pair: "Cow + Leaven",    emoji: "🐮", scene: "A Cow bakes bread and watches the dough rise (Leaven) huge." },
  d7: { pair: "Dragon + 7 Heads", emoji: "🐉", scene: "A Dragon with Seven Heads, each one arguing about dinner." },
  e7: { pair: "Echo + Heaven",   emoji: "🗣️", scene: "A shout “HELLO!” Echoes forever through Heaven. Angels get headaches." },
  f7: { pair: "Fairy + 7 Seas",  emoji: "🧚", scene: "A Fairy sprinkles stardust over the Seven Seas." },
  g7: { pair: "Goose + 7 Dwarfs", emoji: "🦢", scene: "A Goose leads the Seven Dwarfs home, honking the marching tune." },
  h7: { pair: "Hero + 7th Sky",  emoji: "🦸", scene: "A Hero with a “7” on its chest flies in the highest Sky, fighting cloud-villains." },
  // Rank 8 — rhymes with EIGHT / Gate-Ate (Gate/Plate/Late/Crate/Skate/Weight/Great/Ate)
  a8: { pair: "Anchor + Gate",   emoji: "⚓", scene: "An Anchor holds open a giant Gate so ships can sail through." },
  b8: { pair: "Buffalo + Plate", emoji: "🐃", scene: "A 2000-pound Buffalo eats from a giant Plate, napkin tucked, pinky hoof out. “Pass the salt.”" },
  c8: { pair: "Castle + Late",   emoji: "🏰", scene: "A Castle running Late hops on its towers to catch the bus." },
  d8: { pair: "Dolphin + Crate", emoji: "🐬", scene: "A Dolphin leaps out of a Crate of fish at the market." },
  e8: { pair: "Elf + Skate",     emoji: "🧝", scene: "An Elf Skates across an icy lake, leaving sparkle trails." },
  f8: { pair: "Football + Weight", emoji: "🏈", scene: "A Football lifts Weights at the gym to get extra bouncy." },
  g8: { pair: "Genie + Great",   emoji: "🧞", scene: "A Genie grants the wish to be Great — and crowns everyone." },
  h8: { pair: "Hedgehog + Ate",  emoji: "🦔", scene: "A Hedgehog that Ate too many berries rolls home, happily full." },
};

// ---- EASY (Base System): just 8 file-animals x 8 rank-objects (16 things to learn) ----
const EASY_ANIMALS: Record<string, [string, string]> = {
  a: ["Ant", "\ud83d\udc1c"], b: ["Bear", "\ud83d\udc3b"], c: ["Cat", "\ud83d\udc31"], d: ["Dog", "\ud83d\udc36"],
  e: ["Elephant", "\ud83d\udc18"], f: ["Fox", "\ud83e\udd8a"], g: ["Goat", "\ud83d\udc10"], h: ["Horse", "\ud83d\udc34"],
};
const EASY_OBJECTS: Record<number, string> = { 1: "Sun", 2: "Shoe", 3: "Tree", 4: "Door", 5: "Hive", 6: "Sticks", 7: "Heaven", 8: "Gate" };
const EASY_EMOJI: Record<number, string> = { 1: "\u2600\ufe0f", 2: "\ud83d\udc5f", 3: "\ud83c\udf33", 4: "\ud83d\udeaa", 5: "\ud83c\udf6f", 6: "\ud83e\udeb5", 7: "\u2601\ufe0f", 8: "\ud83d\udeaa" };
const EASY: Record<string, Scene> = (() => {
  const out: Record<string, Scene> = {};
  for (const f of "abcdefgh") for (let r = 1; r <= 8; r++) {
    const [animal, emoji] = EASY_ANIMALS[f]!;
    const obj = EASY_OBJECTS[r]!;
    out[f + r] = { pair: `${animal} + ${obj}`, emoji, scene: `Picture the ${animal} with the ${obj}. Say it out loud: \u201c${animal}\u2026 ${obj}!\u201d` };
  }
  return out;
})();

const SET2: Record<string, Scene> = {
  a1: { pair: "Arjuna + Ton", emoji: "🏋️", scene: "Arjuna lifts a Ton of arrows in one hand and shoots them all at once at the demon army!" },
  a2: { pair: "Agni + Bamboo", emoji: "🔥", scene: "Agni the fire god sneezes and a whole grove of Bamboo bursts into cheerful flames!" },
  a3: { pair: "Ashoka + Fee", emoji: "🪙", scene: "Ashoka pays a golden Fee at the temple gate and every stone lion nods thank-you!" },
  a4: { pair: "Anjaneya + Chore", emoji: "🧹", scene: "Anjaneya finishes every Chore in the temple with one swish of his mighty tail!" },
  a5: { pair: "Aditi + Hive", emoji: "🍯", scene: "Aditi the sky goddess pokes a Hive and a hundred bees tickle her nose!" },
  a6: { pair: "Ashwatthama + Fix", emoji: "🔧", scene: "Ashwatthama can Fix any broken bow with just a snap of his glowing fingers!" },
  a7: { pair: "Airavata + Heaven", emoji: "🐘", scene: "Airavata the giant elephant floats up to Heaven on fluffy white clouds!" },
  a8: { pair: "Apsara + Bait", emoji: "🎣", scene: "An Apsara dances on the water and every fish jumps up to grab her sparkling Bait!" },
  b1: { pair: "Bhima + Done", emoji: "✅", scene: "Bhima gobbles a whole feast in one bite and shouts 'Done!' while the cook is still cooking!" },
  b2: { pair: "Brahma + Kangaroo", emoji: "🦘", scene: "Brahma rides a Kangaroo and all four of his heads bounce in different directions!" },
  b3: { pair: "Bali + Ghee", emoji: "🧈", scene: "Bali the mighty king pours golden Ghee that lights up the whole royal court!" },
  b4: { pair: "Brihaspati + Sore", emoji: "📚", scene: "Brihaspati reads so many books his elbows go Sore and he needs a divine massage!" },
  b5: { pair: "Barbarika + Dive", emoji: "🎯", scene: "Barbarika does a perfect Dive into a river with all three of his magic arrows!" },
  b6: { pair: "Budha + Nix", emoji: "🚫", scene: "Budha the planet god shouts 'Nix!' and every demon plan fizzles into dust!" },
  b7: { pair: "Bhishma + Eleven", emoji: "🏹", scene: "Bhishma scores Eleven bullseyes in a row without even looking at the target!" },
  b8: { pair: "Balarama + Fate", emoji: "🌾", scene: "Balarama plows a straight furrow and writes everyone's Fate right into the field!" },
  c1: { pair: "Chitragupta + None", emoji: "0️⃣", scene: "Chitragupta searches for one good deed and finds None — the demon has to start life over!" },
  c2: { pair: "Chandra + Cockatoo", emoji: "🦜", scene: "Chandra the moon god wakes up a chatty Cockatoo who talks the whole night sky to sleep!" },
  c3: { pair: "Chitrasena + Pea", emoji: "🫛", scene: "Chitrasena's flute music makes a tiny Pea grow into a beanstalk in one second!" },
  c4: { pair: "Chamundi + Bore", emoji: "🦁", scene: "Chamundi's fierce yawn is so Boring even the demons fall asleep mid-attack!" },
  c5: { pair: "Chyavana + Five", emoji: "✨", scene: "Chyavana the sage counts Five magic berries and pops them all in his mouth at once!" },
  c6: { pair: "Chakra + Ticks", emoji: "⏰", scene: "Vishnu's spinning Chakra Ticks like a giant clock as it flies through the sky!" },
  c7: { pair: "Chitraka + Leaven", emoji: "🐎", scene: "Chitraka the magical horse eats Leaven bread and bounces up to the treetops!" },
  c8: { pair: "Chandika + Freight", emoji: "🚂", scene: "Chandika loads a whole demon army into a Freight train and rolls it out of the kingdom!" },
  d1: { pair: "Drona + Won", emoji: "🏆", scene: "Drona hands the trophy to the student who Won by shooting an eye off a wooden fish!" },
  d2: { pair: "Draupadi + Peekaboo", emoji: "🙈", scene: "Draupadi's magic bowl plays Peekaboo — each time she opens it, a new feast appears!" },
  d3: { pair: "Durvasa + Chimpanzee", emoji: "🐒", scene: "Durvasa curses a chattering Chimpanzee who then hides in a tree and never speaks again!" },
  d4: { pair: "Dhruva + Adore", emoji: "⭐", scene: "Little Dhruva sits so still even the stars come down to Adore him from close up!" },
  d5: { pair: "Dadhichi + Drive", emoji: "🦴", scene: "Dadhichi gives his bones and the gods use them to Drive the demon car into the lake!" },
  d6: { pair: "Daksha + Wicks", emoji: "🕯️", scene: "Daksha lights sixty candle Wicks all at once with one furious sneeze!" },
  d7: { pair: "Dhanvantari + Oven", emoji: "🍞", scene: "Dhanvantari brews healing bread in a golden Oven that never lets anyone get sick!" },
  d8: { pair: "Devayani + State", emoji: "🏛️", scene: "Devayani insists on an entire State of flowers before she'll pack for the gods!" },
  e1: { pair: "Ekalavya + Spun", emoji: "🌀", scene: "Ekalavya's magic arrow Spun so fast it drilled a hole right through a mountain!" },
  e2: { pair: "Ekadanta + Tattoo", emoji: "🖋️", scene: "Ekadanta Ganesha shows off a new Tattoo of a mouse riding an elephant on his big trunk!" },
  e3: { pair: "Ekavira + Manatee", emoji: "🐋", scene: "Ekavira rides a friendly Manatee across the river to reach the battle in time!" },
  e4: { pair: "Ekapada + Encore", emoji: "🎤", scene: "Ekapada hops on one foot and every crowd shouts 'Encore!' until he does it again!" },
  e5: { pair: "Ekanetra + Alive", emoji: "👁️", scene: "Ekanetra's one giant eye blinks and every sleeping flower wakes up Alive!" },
  e6: { pair: "Ekaaksha + Picks", emoji: "⛏️", scene: "Ekaaksha the one-eyed giant Picks up a whole mountain like it's a marble!" },
  e7: { pair: "Ekashringa + Given", emoji: "🦄", scene: "Ekashringa the one-horned deer has never been Given a gift he can't magically double!" },
  e8: { pair: "Elai + Skate", emoji: "🌿", scene: "The little sage Elai puts leaves on his feet and Skate-slides down the snowy mountain!" },
  f1: { pair: "Fulara + Stun", emoji: "😲", scene: "Fulara the flower goddess is so pretty she Stuns even Indra into speechless awe!" },
  f2: { pair: "Falguni + Taboo", emoji: "🚫", scene: "Falguni Arjuna sings a song so sacred it's Taboo and every demon covers its ears!" },
  f3: { pair: "Feroksha + Honeybee", emoji: "🐝", scene: "The tiny demon Feroksha is chased away by one buzzing Honeybee and runs home crying!" },
  f4: { pair: "Falgu + Score", emoji: "🎼", scene: "The river Falgu hums a heavenly Score that turns every fish into a tiny choir!" },
  f5: { pair: "Falashruti + Jive", emoji: "📜", scene: "Falashruti the sacred text starts to Jive and all the holy words dance off the page!" },
  f6: { pair: "Faraka + Six", emoji: "6️⃣", scene: "The demon Faraka can only count to Six before his fingers get all confused!" },
  f7: { pair: "Fani + Coven", emoji: "🐍", scene: "Fani the serpent slithers through a Coven of witches and turns them all into good fairies!" },
  f8: { pair: "Falindra + Slate", emoji: "🪨", scene: "Falindra lifts a huge Slate and the gods carve tomorrow's news right on top of it!" },
  g1: { pair: "Ganesha + Pun", emoji: "😂", scene: "Ganesha tells a Pun so bad his little mouse falls off the throne giggling!" },
  g2: { pair: "Garuda + Kazoo", emoji: "🎺", scene: "Garuda flies past every mountain playing a golden Kazoo that echoes for a thousand miles!" },
  g3: { pair: "Gandharva + Bumblebee", emoji: "🐝", scene: "A Gandharva plays flute and every Bumblebee in the meadow dances in perfect rhythm!" },
  g4: { pair: "Gayatri + War", emoji: "🙏", scene: "Goddess Gayatri starts to chant and every War in the world pauses to listen!" },
  g5: { pair: "Ghatotkacha + Thrive", emoji: "👹", scene: "Giant Ghatotkacha plants a tiny seed and watches it Thrive into a tree as tall as him!" },
  g6: { pair: "Govinda + Mix", emoji: "🧈", scene: "Govinda Krishna stirs a Mix of butter and every cow gets a squirt on her nose!" },
  g7: { pair: "Guha + Riven", emoji: "🚣", scene: "Guha the ferryman rows so hard his oar leaves the river Riven right down the middle!" },
  g8: { pair: "Gauri + Grate", emoji: "🌸", scene: "Gauri smiles so warmly the icy Grate melts and flowers bloom through every hole!" },
  h1: { pair: "Hanuman + Shun", emoji: "🙅", scene: "Hanuman Shuns all of Ravana's fancy gifts and flies home with his tail held high!" },
  h2: { pair: "Hiranyakashipu + Shampoo", emoji: "👹", scene: "Hiranyakashipu slips on a puddle of Shampoo just as little Prahlada laughs at him!" },
  h3: { pair: "Hayagriva + Referee", emoji: "👨‍⚖️", scene: "Hayagriva the horse-headed god blows a whistle like a Referee and breaks up a demon fight!" },
  h4: { pair: "Hansa + Tore", emoji: "🦢", scene: "The divine Hansa swan Tore straight through a dark cloud and sunshine poured out!" },
  h5: { pair: "Himavat + Chive", emoji: "🏔️", scene: "Mountain king Himavat grows a giant Chive on his snowy peak and uses it as a flag!" },
  h6: { pair: "Hidimba + Styx", emoji: "🌊", scene: "Hidimba the forest friend guides lost souls across the river Styx with a warm smile!" },
  h7: { pair: "Hari + Driven", emoji: "💙", scene: "Hari Vishnu is Driven around the cosmos by Garuda in the fanciest golden chariot ever!" },
  h8: { pair: "Haladhara + Mate", emoji: "🌾", scene: "Haladhara Balarama finds his best Mate in the fields and they plow smiling side by side!" },
};

const SET3: Record<string, Scene> = {
  a1: { pair: "Apple + Onion", emoji: "🧅", scene: "An Apple rolls into a mountain of Onions and cries happy tears down its shiny red cheeks!" },
  a2: { pair: "Avocado + Cuckoo", emoji: "🐦", scene: "An Avocado hops out of a Cuckoo clock every hour shouting 'toast!' at the whole kitchen!" },
  a3: { pair: "Almond + Wee", emoji: "🌰", scene: "An Almond gives a Wee little sneeze and its brown shell pops off like a party hat!" },
  a4: { pair: "Asparagus + Core", emoji: "🥦", scene: "A giant Asparagus stalk stands proudly at the Core of every stir-fry pan on Earth!" },
  a5: { pair: "Artichoke + Hive", emoji: "🌿", scene: "An artichoke crashes into a Hive and bees decorate it with honey drizzle!" },
  a6: { pair: "Apricot + Fix", emoji: "🍑", scene: "A bouncy Apricot tries to Fix the broken jam jar by squishing itself inside the crack!" },
  a7: { pair: "Anchovy + Heaven", emoji: "🐟", scene: "A tiny anchovy floats up to Heaven and sprinkles itself onto a giant pizza cloud!" },
  a8: { pair: "Aubergine + Bait", emoji: "🍆", scene: "A purple Aubergine uses itself as Bait and every hungry pot gapes wide open to catch it!" },
  b1: { pair: "Banana + Salmon", emoji: "🐟", scene: "A Banana lies on a plate of Salmon pretending to be sushi wrapped in a yellow peel!" },
  b2: { pair: "Bagel + Voodoo", emoji: "🥯", scene: "A Bagel does spooky Voodoo dance and every donut in the box starts wiggling in sync!" },
  b3: { pair: "Broccoli + Plea", emoji: "🥦", scene: "A little Broccoli makes a Plea to the chef please please don't overcook me today!" },
  b4: { pair: "Butter + Explore", emoji: "🧈", scene: "A stick of Butter slides across the counter to Explore every cranny of the toaster!" },
  b5: { pair: "Beet + Dive", emoji: "🫚", scene: "A red beet does a belly Dive into a bowl of soup and splashes everyone at the table!" },
  b6: { pair: "Biscuit + Mix", emoji: "🍪", scene: "A hard Biscuit hops into a Mix and turns the whole batter into a crunchy cookie surprise!" },
  b7: { pair: "Blueberry + Eleven", emoji: "🫐", scene: "Exactly Eleven blueberries roll off the counter and hide under the fridge in a row!" },
  b8: { pair: "Bean + Fate", emoji: "🫘", scene: "A single Bean rolls onto the chef's cutting board — its Fate is a big pot of chili!" },
  c1: { pair: "Carrot + Dragon", emoji: "🥕", scene: "A Carrot rides a tiny orange Dragon that breathes carrot-cake smoke over every pastry!" },
  c2: { pair: "Cabbage + Guru", emoji: "🥬", scene: "A wise Cabbage sits like a Guru on a mountain and teaches the sprouts to meditate!" },
  c3: { pair: "Cashew + Spree", emoji: "🌰", scene: "A Cashew goes on a shopping Spree at the snack aisle and comes home with everything!" },
  c4: { pair: "Celery + Restore", emoji: "🥬", scene: "A Celery stalk drops into water and starts to Restore itself back to crunchy freshness!" },
  c5: { pair: "Cheese + Five", emoji: "🧀", scene: "A wedge of cheese gives a high Five to every mouse who runs through the kitchen tonight!" },
  c6: { pair: "Cherry + Kicks", emoji: "🍒", scene: "A Cherry Kicks its stem off and doorbell-rings the pie shell asking to jump inside!" },
  c7: { pair: "Cinnamon + Leaven", emoji: "🧂", scene: "A cinnamon roll puffs up with Leaven until it is bigger than the oven and floats away!" },
  c8: { pair: "Cucumber + Freight", emoji: "🥒", scene: "A Cucumber loads itself onto a Freight train and rolls straight to the salad express!" },
  d1: { pair: "Doughnut + Cannon", emoji: "🍩", scene: "A Doughnut fires from a Cannon and splats icing rings across the whole ceiling!" },
  d2: { pair: "Dumpling + Menu", emoji: "🥟", scene: "A Dumpling steams open and every dish on the Menu comes tumbling out one by one!" },
  d3: { pair: "Date + Glee", emoji: "🌴", scene: "A sticky Date squeals with Glee as it slides straight into the palm-sugar cake!" },
  d4: { pair: "Dragonfruit + Ignore", emoji: "🐉", scene: "A Dragonfruit tries to Ignore every knife but its bright pink skin gives it away!" },
  d5: { pair: "Daikon + Drive", emoji: "🥕", scene: "A white daikon buckles up and goes for a Drive through the veggie drawer honking!" },
  d6: { pair: "Dulce + Sticks", emoji: "🍬", scene: "A block of Dulce de leche melts around some Sticks and every kid runs over with a grin!" },
  d7: { pair: "Durian + Heaven", emoji: "🌵", scene: "A spiky durian floats up to Heaven and every angel plugs its nose politely!" },
  d8: { pair: "Dill + State", emoji: "🌿", scene: "A bunch of Dill declares a whole State inside a pickle jar with tiny tangy flags!" },
  e1: { pair: "Egg + Wagon", emoji: "🥚", scene: "An Egg loads itself into a Wagon and rolls off to the omelette parade cheering!" },
  e2: { pair: "Edamame + Igloo", emoji: "🫛", scene: "An Edamame pod builds a tiny Igloo out of frozen pea shells and moves in for winter!" },
  e3: { pair: "Éclair + Jubilee", emoji: "🍫", scene: "A chocolate Éclair leads a golden Jubilee parade through the dessert shop windows!" },
  e4: { pair: "Endive + Yore", emoji: "🥬", scene: "A curly Endive tells stories of Yore when salads ruled every royal banquet table!" },
  e5: { pair: "Espresso + Alive", emoji: "☕", scene: "A tiny espresso cup wakes everything Alive by buzzing around the room super fast!" },
  e6: { pair: "Enchilada + Chicks", emoji: "🌯", scene: "A rolled Enchilada opens and out pop six baby Chicks all wearing tiny sombreros!" },
  e7: { pair: "Elderberry + Eleven", emoji: "🫐", scene: "Exactly Eleven Elderberries pop out of a jam jar and dance a purple line-up!" },
  e8: { pair: "Empanada + Slate", emoji: "🥟", scene: "A golden Empanada wipes the Slate clean by eating every crumb on the counter!" },
  f1: { pair: "Fig + Melon", emoji: "🍇", scene: "A plump Fig climbs into a hollow Melon and turns it into a fruit-disco ball!" },
  f2: { pair: "Falafel + Vindaloo", emoji: "🧆", scene: "A round Falafel rolls straight into a bowl of spicy Vindaloo and comes out breathing fire!" },
  f3: { pair: "Fennel + Jamboree", emoji: "🌿", scene: "A frilly Fennel throws a huge herb-garden Jamboree and every leaf comes dancing!" },
  f4: { pair: "Focaccia + Fore", emoji: "🍞", scene: "A dimply Focaccia shouts 'Fore!' as it flies off the pizza paddle onto the lawn!" },
  f5: { pair: "Frankfurter + Jive", emoji: "🌭", scene: "A frankfurter does the Jive in the frying pan and kicks sizzling oil onto the ceiling!" },
  f6: { pair: "Frittata + Tricks", emoji: "🍳", scene: "A Frittata learns circus Tricks and flips itself spinning before landing perfectly flat!" },
  f7: { pair: "Freekeh + Heaven", emoji: "🌾", scene: "A grain of Freekeh sails up to Heaven in a thimble boat hunting the world's biggest soup!" },
  f8: { pair: "Frosting + Mate", emoji: "🎂", scene: "A blob of Frosting finds its true Mate on a cupcake and they swirl together forever!" },
  g1: { pair: "Garlic + Lemon", emoji: "🧄", scene: "A Garlic clove teams up with a Lemon and every vampire flees the salad in tears!" },
  g2: { pair: "Grape + Fondue", emoji: "🍇", scene: "A Grape cannonballs into a Fondue pot and splashes warm chocolate on every strawberry!" },
  g3: { pair: "Ginger + Employee", emoji: "🫚", scene: "A Ginger root becomes Employee of the Month for spicing every dish with one snap!" },
  g4: { pair: "Guava + Gore", emoji: "🍈", scene: "A round Guava splits open with a bit of red Gore that turns out to be just juicy pulp!" },
  g5: { pair: "Granola + Thrive", emoji: "🌾", scene: "A granola cluster plants itself in yogurt and starts to Thrive, growing crunchier each day!" },
  g6: { pair: "Grapefruit + Licks", emoji: "🍊", scene: "A Grapefruit Licks the sugar bowl and its sour face turns into the biggest sweet smile!" },
  g7: { pair: "Gouda + Given", emoji: "🧀", scene: "A wheel of Gouda has Given itself away to every mouse in the pantry as free breakfast!" },
  g8: { pair: "Gnocchi + Skate", emoji: "🥟", scene: "A tiny Gnocchi pillow puts on Skates and does a perfect figure-eight on the pasta dish!" },
  h1: { pair: "Honey + Weapon", emoji: "🍯", scene: "A jar of Honey becomes a sticky Weapon and traps every ant in golden goo!" },
  h2: { pair: "Hotdog + Kazoo", emoji: "🌭", scene: "A Hotdog toots a Kazoo tune from inside its bun and the whole plate hums along!" },
  h3: { pair: "Hummus + Chickadee", emoji: "🫙", scene: "A bowl of Hummus is guarded by a tiny Chickadee who won't let anyone dip without asking!" },
  h4: { pair: "Hazelnut + Oar", emoji: "🌰", scene: "A Hazelnut hops into a walnut-shell boat and rows away with a toothpick for an Oar!" },
  h5: { pair: "Halloumi + Chive", emoji: "🧀", scene: "A squeaky Halloumi slice grows a long Chive mustache and admires itself in the frying pan!" },
  h6: { pair: "Hoisin + Bricks", emoji: "🫙", scene: "A bottle of Hoisin sauce builds sticky Bricks and glues an entire dumpling castle together!" },
  h7: { pair: "Herring + Coven", emoji: "🐟", scene: "A pickled Herring joins a witch's Coven and turns the cauldron into a fishy stew!" },
  h8: { pair: "Hash Brown + Grate", emoji: "🥔", scene: "A crispy Hash Brown slides through the Grate and comes out crunchier than ever!" },
};

const SET4: Record<string, Scene> = {
  a1: { pair: "Astronaut + Marathon", emoji: "🏃", scene: "An Astronaut runs a Marathon in zero gravity and finishes the race a whole day early!" },
  a2: { pair: "Alien + Zulu", emoji: "👽", scene: "A googly-eyed Alien greets Earth in perfect Zulu and everyone cheers!" },
  a3: { pair: "Asteroid + Absentee", emoji: "☄️", scene: "A giant Asteroid is the Absentee at every planet's birthday but always sends stardust gifts!" },
  a4: { pair: "Apollo + Dinosaur", emoji: "🚀", scene: "The Apollo rocket lands near a friendly Dinosaur and gives it a ride to the moon!" },
  a5: { pair: "Antimatter + Hive", emoji: "💥", scene: "Antimatter touches a beehive and poof — the bees vanish into sparkles!" },
  a6: { pair: "Atmosphere + Fix", emoji: "🌌", scene: "The Atmosphere gets a leak and every astronaut runs up to Fix it with sky-blue tape!" },
  a7: { pair: "Andromeda + Heaven", emoji: "🌠", scene: "The Andromeda galaxy floats up to Heaven and knocks on the cloud door!" },
  a8: { pair: "Antares + Rate", emoji: "⭐", scene: "The giant red star Antares glows at a Rate faster than every other star in the sky!" },
  b1: { pair: "Blackhole + Skeleton", emoji: "🕳️", scene: "A Blackhole swallows a Skeleton and burps out a hundred rattling bones across the galaxy!" },
  b2: { pair: "Blastoff + Cashew", emoji: "🚀", scene: "A rocket Blasts off shaped like a giant Cashew and every squirrel goes wild watching!" },
  b3: { pair: "Booster + Guarantee", emoji: "🐝", scene: "A rocket Booster carries a Guarantee that every passenger arrives safely with a smile!" },
  b4: { pair: "Bigbang + Corridor", emoji: "💥", scene: "The Big Bang happened at the end of a long Corridor and knocked open every star's door!" },
  b5: { pair: "Bugbot + Dive", emoji: "🤖", scene: "A tiny space bug robot does a belly Dive into a moon puddle and splashes stars!" },
  b6: { pair: "Beacon + Mix", emoji: "🔦", scene: "A space Beacon spins its rainbow lights and Mixes every color into a cosmic disco!" },
  b7: { pair: "Bytestar + Eleven", emoji: "💫", scene: "Bytestar the robot counts to Eleven but keeps floating away before he finishes!" },
  b8: { pair: "Borealis + Date", emoji: "🌈", scene: "The Northern Borealis lights show up right on their Date and paint the whole sky green!" },
  c1: { pair: "Comet + Cauldron", emoji: "☄️", scene: "A Comet dives into a witch's Cauldron and comes out sparkling with midnight potion!" },
  c2: { pair: "Cosmonaut + Kudzu", emoji: "👨‍🚀", scene: "A Cosmonaut lands in a jungle of Kudzu vines and swings through space like Tarzan!" },
  c3: { pair: "Crater + Trainee", emoji: "🌑", scene: "A moon Crater teaches every Trainee astronaut how to bounce landing perfectly first try!" },
  c4: { pair: "Capsule + Meteor", emoji: "🛸", scene: "The space Capsule high-fives a passing Meteor and both leave sparkle streaks behind!" },
  c5: { pair: "Constellation + Five", emoji: "⭐", scene: "A Constellation shaped like a hand gives a high Five to every passing spaceship!" },
  c6: { pair: "Craterbot + Chicks", emoji: "🤖", scene: "A Crater robot hatches five fluffy Chicks from moon eggs and does a happy dance!" },
  c7: { pair: "Cybermoon + Leaven", emoji: "🌕", scene: "The cyber moon uses Leaven to make the fluffiest moon bread in the whole galaxy!" },
  c8: { pair: "Corona + Crate", emoji: "🌟", scene: "The sun's Corona ships fresh sunlight in a golden Crate to every dark corner of space!" },
  d1: { pair: "Droid + Baron", emoji: "🤖", scene: "A Droid dresses up as a Baron and demands every rocket bow before it takes off!" },
  d2: { pair: "Darkstar + Impromptu", emoji: "⭐", scene: "A Dark star performs an Impromptu song and every planet has to dance the rest of the night!" },
  d3: { pair: "Debris + Devotee", emoji: "🌊", scene: "Every piece of space Debris is a Devotee of the vacuum cleaner satellite that swoops by!" },
  d4: { pair: "Dwarf-planet + Metaphor", emoji: "🪐", scene: "A Dwarf planet is a Metaphor for a marble — small but full of secret worlds inside!" },
  d5: { pair: "Dustcloud + Drive", emoji: "☁️", scene: "A fluffy Dust cloud sits in the driver's seat and takes a rocket for a Drive!" },
  d6: { pair: "Darkmatter + Ticks", emoji: "💥", scene: "Dark matter Ticks like a spooky clock in the deepest black corners of space!" },
  d7: { pair: "Deepspace + Given", emoji: "👾", scene: "Deep space has Given every planet a bright shiny star just for company at night!" },
  d8: { pair: "Docking-port + Debate", emoji: "🛸", scene: "The Docking port hosts a Debate over which rocket parks first and everyone cheers loudly!" },
  e1: { pair: "Eclipse + Falcon", emoji: "🌑", scene: "The Eclipse hides behind a giant space Falcon and only its glowing edge peeks out!" },
  e2: { pair: "Exoplanet + Cockapoo", emoji: "🪐", scene: "An Exoplanet is home to nothing but Cockapoo puppies who all bark at Earth!" },
  e3: { pair: "Earthling + Nominee", emoji: "🌍", scene: "An Earthling is the Nominee for Best Space Tourist and floats up to accept the award!" },
  e4: { pair: "EVA-suit + Emperor", emoji: "👨‍🚀", scene: "An Emperor tries on the EVA suit and demands more space stars sewn onto his cape!" },
  e5: { pair: "Europa + Alive", emoji: "🌊", scene: "The moon Europa cracks open its icy shell and something Alive pops out and waves hi!" },
  e6: { pair: "Engine + Fix", emoji: "🔧", scene: "The rocket Engine needs a Fix so an alien uses a banana as a wrench and it works!" },
  e7: { pair: "Enceladus + Heaven", emoji: "💫", scene: "Enceladus shoots ice geysers so high they tickle the gates of space Heaven!" },
  e8: { pair: "Exomoon + Estate", emoji: "🌙", scene: "A tiny Exomoon owns a huge Estate of asteroids that circle it like a fairytale garden!" },
  f1: { pair: "Firestar + Bacon", emoji: "⭐", scene: "A fiery Firestar loves Bacon so much it sizzles bacon strips across every galaxy!" },
  f2: { pair: "Fuelcell + Timbuktu", emoji: "🔋", scene: "A rocket Fuel cell has enough juice to travel all the way to Timbuktu and back!" },
  f3: { pair: "Flyby + Committee", emoji: "🚀", scene: "Every planet Flyby is voted on by a Committee of space ants who love waving flags!" },
  f4: { pair: "Frostmoon + Sophomore", emoji: "🌙", scene: "The Frostmoon is a Sophomore in Star School and hands in ice-covered homework late!" },
  f5: { pair: "Flare + Jive", emoji: "🌟", scene: "A solar Flare does the Jive so energetically it powers the whole space station!" },
  f6: { pair: "Flightpath + Sticks", emoji: "🛸", scene: "A Flightpath is marked by glowing Sticks that only rockets can see in the deep dark!" },
  f7: { pair: "Farside + Coven", emoji: "🌑", scene: "The far side of the moon hides a Coven of moon-witches who bake cheese under starlight!" },
  f8: { pair: "Fusioncore + Create", emoji: "⚛️", scene: "A Fusion core can Create a brand-new star from just a spoonful of hydrogen!" },
  g1: { pair: "Galaxy + Ribbon", emoji: "🌌", scene: "A Galaxy is a long silvery Ribbon that ties around planets like birthday presents!" },
  g2: { pair: "Graviton + Boohoo", emoji: "💙", scene: "A Graviton feels lonely and cries a big Boohoo that pulls every planet closer for a hug!" },
  g3: { pair: "Geostationary + Trustee", emoji: "🛰️", scene: "A Geostationary satellite is the Trustee of every text message zooming across the world!" },
  g4: { pair: "Gascloud + Furthermore", emoji: "☁️", scene: "A giant Gas cloud says 'Furthermore!' and swallows another whole planet just to make its point!" },
  g5: { pair: "Gravitywaves + Thrive", emoji: "🌊", scene: "Gravity waves Thrive when they find a bouncy castle in deep space and jump all day!" },
  g6: { pair: "Globularcluster + Tricks", emoji: "⭐", scene: "A Globular cluster performs magic Tricks and pulls a fresh comet from behind Saturn's ear!" },
  g7: { pair: "Ganymede + Riven", emoji: "🌕", scene: "The moon Ganymede is Riven by ancient cracks that light up whenever a spaceship flies over!" },
  g8: { pair: "Gravitylens + Update", emoji: "🔭", scene: "A Gravity lens gets a magic Update and now shows every hidden star in the universe!" },
  h1: { pair: "Hyperdrive + Wonton", emoji: "🚀", scene: "The Hyperdrive is powered by one perfectly folded Wonton dumpling from a cosmic kitchen!" },
  h2: { pair: "Hubble + Hullabaloo", emoji: "🔭", scene: "The Hubble telescope catches a Hullabaloo of aliens partying on a purple planet!" },
  h3: { pair: "Halo + Vietnamese", emoji: "😇", scene: "A planet's glowing Halo learns to speak Vietnamese to greet every visiting spaceship!" },
  h4: { pair: "Hotjupiter + Nevermore", emoji: "🪐", scene: "Hot Jupiter's storms rage Nevermore since a giant fan-shaped moon cooled them down!" },
  h5: { pair: "Hyperspace + Chive", emoji: "🌌", scene: "Hyperspace smells exactly like Chive and every astronaut gets very hungry travelling through it!" },
  h6: { pair: "Heliopause + Bricks", emoji: "🍭", scene: "The Heliopause is built of glowing Bricks that no probe can climb past without permission!" },
  h7: { pair: "Horizon-event + Eleven", emoji: "🕳️", scene: "The event horizon of a black hole makes every clock jump straight to Eleven o'clock forever!" },
  h8: { pair: "Halleycomet + Trait", emoji: "☄️", scene: "Halley's comet has one very famous Trait — it always comes back exactly seventy-six years later!" },
};

const SET5: Record<string, Scene> = {
  a1: { pair: "Anglerfish + Ton", emoji: "🐟", scene: "An Anglerfish glows so bright it lights a whole Ton of glittering fish at once!" },
  a2: { pair: "Anemone + Chew", emoji: "🌺", scene: "An Anemone Chews softly on tiny shrimp snacks it caught with its waving arms!" },
  a3: { pair: "Anchor + Bee", emoji: "⚓", scene: "A rusty Anchor is home to one busy Bee-shaped fish that buzzes around it!" },
  a4: { pair: "Amberjack + War", emoji: "🐠", scene: "An Amberjack races into a War with a shark and wins by wiggling its tail super fast!" },
  a5: { pair: "Algae + Hive", emoji: "🌿", scene: "A big patch of Algae is actually a Hive where tiny sea bees make salty honey!" },
  a6: { pair: "Abalone + Bricks", emoji: "🐚", scene: "An Abalone shell stacks pearl Bricks and builds a shiny castle on the ocean floor!" },
  a7: { pair: "Atlantis + Heaven", emoji: "🏛️", scene: "Atlantis floats up to Heaven and the fish wave goodbye from the clouds!" },
  a8: { pair: "Albacore + Skate", emoji: "🐟", scene: "An Albacore tuna puts on tiny ice Skates and glides across a frozen tide pool!" },
  b1: { pair: "Blowfish + Bun", emoji: "🐡", scene: "A Blowfish puffs up so big it looks exactly like a giant sesame Bun!" },
  b2: { pair: "Barnacle + Blue", emoji: "🦞", scene: "A Barnacle turns bright Blue when it hitches a ride on a whale's back!" },
  b3: { pair: "Beluga + Ghee", emoji: "🐋", scene: "A Beluga whale slides through the water like a giant scoop of golden Ghee!" },
  b4: { pair: "Barracuda + Roar", emoji: "🐟", scene: "A Barracuda opens its toothy mouth and lets out a bubbly Roar that shakes the reef!" },
  b5: { pair: "Blue Whale + Dive", emoji: "🐳", scene: "A Blue whale does a perfect Olympic Dive and makes a splash the size of a city!" },
  b6: { pair: "Brittlestar + Mix", emoji: "⭐", scene: "A Brittlestar tumbles into a swirl and Mixes up its arms into a five-pointed jumble!" },
  b7: { pair: "Bioluminescence + Eleven", emoji: "✨", scene: "Eleven glowing jellyfish line up to spell out their favorite number!" },
  b8: { pair: "Box Jellyfish + Plate", emoji: "🪼", scene: "A Box jellyfish puts a tiny Plate on its head and pretends to be a fancy waiter!" },
  c1: { pair: "Clownfish + Fun", emoji: "🐠", scene: "A Clownfish throws a party because Fun is its whole entire job!" },
  c2: { pair: "Crab + Shoe", emoji: "🦀", scene: "A Crab tries on a tiny Shoe and marches around the sand like a fancy general!" },
  c3: { pair: "Coral + Pea", emoji: "🪸", scene: "A piece of Coral hides a tiny Pea in its holes and grows it into a shiny pearl!" },
  c4: { pair: "Catfish + Snore", emoji: "🐟", scene: "A Catfish falls asleep on a lily pad and Snores so loud it makes bubbles!" },
  c5: { pair: "Conch + Five", emoji: "🐚", scene: "A Conch shell holds up Five fingers and shouts it can hear the whole ocean!" },
  c6: { pair: "Cuttlefish + Chicks", emoji: "🦑", scene: "A Cuttlefish changes color to look like six fluffy Chicks and fools everyone!" },
  c7: { pair: "Clam + Leaven", emoji: "🦪", scene: "A Clam adds Leaven to its shell and watches itself puff up like fresh bread!" },
  c8: { pair: "Chambered Nautilus + Late", emoji: "🐚", scene: "A Chambered nautilus keeps spiraling back because it is always very Late!" },
  d1: { pair: "Dolphin + Run", emoji: "🐬", scene: "A Dolphin leaps out of the water and goes for a Run along the beach on its tail!" },
  d2: { pair: "Dugong + Zoo", emoji: "🐄", scene: "A Dugong wanders into the Zoo and every animal comes over to say a friendly hello!" },
  d3: { pair: "Deep-sea Diver + Fee", emoji: "🤿", scene: "A Deep-sea diver pays a small Fee at the ocean gate and gets to see all the fish!" },
  d4: { pair: "Dragonfish + Store", emoji: "🐉", scene: "A Dragonfish opens a Store selling glowing lures and every fish wants to buy one!" },
  d5: { pair: "Damselfish + Drive", emoji: "🐟", scene: "A tiny Damselfish sits behind a wheel and takes a Drive through the coral reef!" },
  d6: { pair: "Driftwood + Sticks", emoji: "🪵", scene: "A piece of Driftwood joins two Sticks and builds a tiny sailboat for a hermit crab!" },
  d7: { pair: "Deadlights + Heaven", emoji: "💀", scene: "A shipwreck's Deadlights glow all the way up to Heaven guiding lost sailors home!" },
  d8: { pair: "Dory + Great", emoji: "🐟", scene: "A forgetful fish named Dory forgets her own name and then remembers it is Great!" },
  e1: { pair: "Eel + Won", emoji: "⚡", scene: "An electric Eel zaps a shiny gold cup because it Won first place in the sea Olympics!" },
  e2: { pair: "Emperor Shrimp + Crew", emoji: "🦐", scene: "An Emperor shrimp gathers a tiny Crew of plankton and sets sail on a leaf!" },
  e3: { pair: "Estuarine Crocodile + Tea", emoji: "🐊", scene: "An Estuarine crocodile sits in a tiny chair and sips a cup of salty sea Tea!" },
  e4: { pair: "Epaulette Shark + Boar", emoji: "🦈", scene: "An Epaulette shark walks on its fins like a friendly little Boar of the sea floor!" },
  e5: { pair: "Electric Ray + Alive", emoji: "⚡", scene: "An Electric ray zaps itself by mistake and shouts I am very much Alive!" },
  e6: { pair: "Eelgrass + Fix", emoji: "🌿", scene: "A tangle of Eelgrass wraps around a submarine engine and tries hard to Fix it!" },
  e7: { pair: "Expedition Ship + Heaven", emoji: "🚢", scene: "An Expedition ship floats so high on a wave it bumps its head on Heaven!" },
  e8: { pair: "Echinoderm + Gate", emoji: "⭐", scene: "A spiny Echinoderm stands at the sea Gate and pokes any grumpy fish that tries to leave!" },
  f1: { pair: "Flounder + Nun", emoji: "🐟", scene: "A Flounder wears a black and white habit and everyone thinks it is a tiny Nun!" },
  f2: { pair: "Frogfish + Stew", emoji: "🐸", scene: "A lumpy Frogfish stirs a giant Stew and all the seaweed dances in the bubbling pot!" },
  f3: { pair: "Flying Fish + Flea", emoji: "🐟", scene: "A Flying fish soars out of the water and nearly lands on a very surprised Flea!" },
  f4: { pair: "Fangtooth + Snore", emoji: "🦷", scene: "A Fangtooth Snores so loudly its huge teeth rattle and scare every deep-sea shrimp!" },
  f5: { pair: "Firefly Squid + Jive", emoji: "🦑", scene: "A glowing Firefly squid blinks its lights and does the Jive on the ocean floor!" },
  f6: { pair: "Feather Star + Tricks", emoji: "🌟", scene: "A Feather star waves its frilly arms and does magic Tricks that dazzle every fish!" },
  f7: { pair: "Fisherman + Seven Seas", emoji: "🎣", scene: "An old Fisherman sails all Seven Seas but only ever catches one tiny sardine!" },
  f8: { pair: "Frigate Bird + Ate", emoji: "🐦", scene: "A Frigate bird Ate a whole flying fish in one gulp and burps a rainbow feather!" },
  g1: { pair: "Giant Squid + Gun", emoji: "🦑", scene: "A Giant squid holds a water Gun in each of its ten arms and soaks everybody!" },
  g2: { pair: "Grouper + Glue", emoji: "🐟", scene: "A chubby Grouper drops a bottle of Glue and every fish gets stuck in a giggling clump!" },
  g3: { pair: "Ghost Shrimp + Ski", emoji: "👻", scene: "A see-through Ghost shrimp straps on tiny Skis and slaloms down a kelp slope!" },
  g4: { pair: "Gulper Eel + More", emoji: "🐍", scene: "A Gulper eel opens its enormous mouth and yells 'More fish please!' at the whole ocean!" },
  g5: { pair: "Goby + Thrive", emoji: "🐟", scene: "A tiny Goby fish reads a book called How To Thrive In A Very Big Ocean!" },
  g6: { pair: "Greenling + Kicks", emoji: "🐟", scene: "A Greenling Kicks up sand into a swirling green cloud and everyone yells 'do it again!'" },
  g7: { pair: "Grotto + Coven", emoji: "🏔️", scene: "A dark ocean Grotto hides a Coven of witch-fish brewing bubbly seaweed potion!" },
  g8: { pair: "Great White + Weight", emoji: "🦈", scene: "A Great White shark shows off its Weight by lifting a whole shipwreck with its nose!" },
  h1: { pair: "Hammerhead + Swan", emoji: "🦈", scene: "A Hammerhead shark tries a graceful Swan dive but belly-flops instead!" },
  h2: { pair: "Hermit Crab + True", emoji: "🦀", scene: "A Hermit crab shows all the sea shells its True cozy home is inside an old boot!" },
  h3: { pair: "Horseshoe Crab + Knee", emoji: "🦀", scene: "A Horseshoe crab tries to bend its Knee but realizes it does not have one!" },
  h4: { pair: "Humpback Whale + Bore", emoji: "🐋", scene: "A Humpback whale sings a whole song so long every fish nearly falls asleep from Bore!" },
  h5: { pair: "Hagfish + Chive", emoji: "🐟", scene: "A slimy Hagfish grows a little Chive on its nose and calls itself a gourmet fish!" },
  h6: { pair: "Hydrothermal Vent + Licks", emoji: "🌋", scene: "A Hydrothermal vent Licks its hot smoky lips and says dinner is served down here!" },
  h7: { pair: "Hull + Given", emoji: "🚢", scene: "A shipwreck Hull has Given every fish a cozy new home to hide inside!" },
  h8: { pair: "Halibut + Late", emoji: "🐟", scene: "A flat Halibut swims to breakfast very Late and finds all the shrimp already gone!" },
};

const SET6: Record<string, Scene> = {
  a1: { pair: "Ape + Sun", emoji: "☀️", scene: "An ape does a silly dance under the blazing Sun." },
  a2: { pair: "Antelope + Zoo", emoji: "🦌", scene: "An antelope leaps over the fence straight into the Zoo." },
  a3: { pair: "Anaconda + Tree", emoji: "🐍", scene: "An anaconda coils around the tallest Tree and waves hello." },
  a4: { pair: "Armadillo + Door", emoji: "🚪", scene: "An armadillo knocks on a tiny jungle Door with its hard nose." },
  a5: { pair: "Aardvark + Hive", emoji: "🐝", scene: "An aardvark sticks its long nose right into a buzzing Hive." },
  a6: { pair: "Anteater + Sticks", emoji: "🪵", scene: "An anteater juggles six muddy Sticks with its sticky tongue." },
  a7: { pair: "Aviary + Heaven", emoji: "☁️", scene: "The Aviary floats up up up and almost reaches Heaven." },
  a8: { pair: "Acacia + Gate", emoji: "🌲", scene: "A tall acacia tree crashes through the safari Gate." },
  b1: { pair: "Buffalo + Bun", emoji: "🦬", scene: "A buffalo sits on a hot cross Bun and squishes it flat." },
  b2: { pair: "Baboon + Glue", emoji: "🐒", scene: "A baboon sits in a puddle of purple Glue and cannot get up." },
  b3: { pair: "Beetle + Bee", emoji: "🐛", scene: "A giant jungle beetle chases a Bee around and around." },
  b4: { pair: "Boa + Floor", emoji: "🐍", scene: "A boa constrictor slides across the tent Floor and tickles everyone." },
  b5: { pair: "Bush + Dive", emoji: "🌿", scene: "A monkey does a spectacular Dive straight into a leafy Bush." },
  b6: { pair: "Bird + Bricks", emoji: "🦜", scene: "A colorful jungle bird builds its nest out of tiny red Bricks." },
  b7: { pair: "Bat + Eleven", emoji: "🦇", scene: "Eleven bats hang upside down all in a row and count themselves." },
  b8: { pair: "Boar + Plate", emoji: "🐗", scene: "A wild boar eats every banana off a giant Plate in one gulp." },
  c1: { pair: "Croc + Fun", emoji: "🐊", scene: "A crocodile wearing a party hat has so much Fun at the river." },
  c2: { pair: "Chimp + Stew", emoji: "🐒", scene: "A chimp stirs a bubbling jungle Stew with a long stick." },
  c3: { pair: "Cobra + Key", emoji: "🐍", scene: "A cobra holds a golden Key in its mouth and hisses loudly." },
  c4: { pair: "Crane + Snore", emoji: "🦩", scene: "A tall crane bird falls asleep standing up and lets out a huge Snore." },
  c5: { pair: "Cougar + Five", emoji: "🐆", scene: "A cougar high-Fives five explorer kids with its big paw." },
  c6: { pair: "Chameleon + Chicks", emoji: "🦎", scene: "A chameleon turns rainbow colours to impress six fluffy Chicks." },
  c7: { pair: "Cassowary + Leaven", emoji: "🐦", scene: "A cassowary kneads bread dough and waits for the Leaven to rise." },
  c8: { pair: "Caterpillar + Late", emoji: "🐛", scene: "A caterpillar runs as fast as it can because it is always Late." },
  d1: { pair: "Dingo + Run", emoji: "🐕", scene: "A dingo does a funny wiggly Run straight past the campfire." },
  d2: { pair: "Deer + Moo", emoji: "🦌", scene: "A deer tries very hard to Moo like a cow and confuses everyone." },
  d3: { pair: "Dolphin + Sea", emoji: "🐬", scene: "A dolphin leaps out of the jungle river into the sparkling Sea." },
  d4: { pair: "Dragon + Roar", emoji: "🐉", scene: "A tiny jungle dragon lets out the biggest Roar you ever heard." },
  d5: { pair: "Dung Beetle + Drive", emoji: "🐞", scene: "A dung beetle learns to Drive a little jeep through the mud." },
  d6: { pair: "Duck + Kicks", emoji: "🦆", scene: "A duck Kicks six mud pies into the air with its webbed feet." },
  d7: { pair: "Dog + Seven Heads", emoji: "🐕", scene: "A safari dog imagines it has Seven Heads and barks in all directions." },
  d8: { pair: "Dhole + Crate", emoji: "🐕", scene: "A wild dhole pup climbs into a wooden Crate and peeks out." },
  e1: { pair: "Elephant + One", emoji: "🐘", scene: "One enormous elephant trips over its own trunk and sits down hard." },
  e2: { pair: "Eagle + Crew", emoji: "🦅", scene: "An eagle boss leads its whole Crew of birds over the treetops." },
  e3: { pair: "Explorer + Tea", emoji: "🧭", scene: "A sweaty explorer stops in the jungle and makes a cup of Tea." },
  e4: { pair: "Emu + More", emoji: "🦤", scene: "An emu gulps down a bowl of bugs and immediately squawks for More." },
  e5: { pair: "Elk + Alive", emoji: "🦌", scene: "An elk jumps so high it cannot believe it is Alive when it lands." },
  e6: { pair: "Egret + Fix", emoji: "🦢", scene: "An egret tries to Fix the explorer's broken compass with its beak." },
  e7: { pair: "Elephant Calf + Heaven", emoji: "🐘", scene: "A tiny elephant calf floats on bubbles all the way up to Heaven." },
  e8: { pair: "Eland + Skate", emoji: "🦌", scene: "An eland straps leaves to its hooves and tries to Skate on the mud." },
  f1: { pair: "Fox + Nun", emoji: "🦊", scene: "A jungle fox bumps into a Nun and spills her mango juice everywhere." },
  f2: { pair: "Flamingo + Chew", emoji: "🦩", scene: "A flamingo Chews pink bubble gum that matches its feathers." },
  f3: { pair: "Frog + Flea", emoji: "🐸", scene: "A fat frog swallows a Flea by accident and hiccups for an hour." },
  f4: { pair: "Fruit Bat + Store", emoji: "🦇", scene: "A fruit bat opens a tiny jungle Store selling mangoes and bugs." },
  f5: { pair: "Firefly + Jive", emoji: "✨", scene: "A hundred fireflies light up and Jive dance all through the night." },
  f6: { pair: "Fish Eagle + Tricks", emoji: "🦅", scene: "A fish eagle does seven Tricks in the air before catching its lunch." },
  f7: { pair: "Flying Squirrel + Seven Seas", emoji: "🐿️", scene: "A flying squirrel dreams it has sailed all the Seven Seas on a leaf." },
  f8: { pair: "Fennec + Weight", emoji: "🦊", scene: "A tiny fennec fox lifts a huge Weight and everyone cheers wildly." },
  g1: { pair: "Gorilla + Gun", emoji: "🦍", scene: "A gorilla finds a water Gun and soaks every explorer in the camp." },
  g2: { pair: "Giraffe + Blue", emoji: "🦒", scene: "A giraffe paints its long neck bright Blue and feels very fancy." },
  g3: { pair: "Gecko + Ski", emoji: "🦎", scene: "A gecko straps two sticks to its feet and tries to Ski down a vine." },
  g4: { pair: "Gazelle + Pour", emoji: "🦌", scene: "A gazelle Pours a whole waterfall of juice into a tiny cup." },
  g5: { pair: "Gnu + Thrive", emoji: "🐃", scene: "A gnu eats every leaf in sight and absolutely Thrives in the jungle." },
  g6: { pair: "Grasshopper + Mix", emoji: "🦗", scene: "A grasshopper DJ Mixes jungle beats by clicking its legs together." },
  g7: { pair: "Gibbon + Seven Dwarfs", emoji: "🐒", scene: "A gibbon swings into a treehouse where Seven Dwarfs are having dinner." },
  g8: { pair: "Giant Tortoise + Great", emoji: "🐢", scene: "A giant tortoise wins the race and everyone shouts that it is Great." },
  h1: { pair: "Hippo + Swan", emoji: "🦛", scene: "A hippo tries to swim gracefully like a Swan but makes huge splashes." },
  h2: { pair: "Hyena + Shoe", emoji: "🐾", scene: "A hyena laughs so hard it falls right into a giant muddy Shoe." },
  h3: { pair: "Hornbill + Knee", emoji: "🦜", scene: "A hornbill bonks itself on the Knee with its enormous beak." },
  h4: { pair: "Hog + Boar", emoji: "🐗", scene: "A hog and a Boar bump snouts and both tumble into the river." },
  h5: { pair: "Heron + Chive", emoji: "🦢", scene: "A heron seasons its fish with a sprig of Chive and looks very pleased." },
  h6: { pair: "Hamster + Licks", emoji: "🐹", scene: "A jungle hamster Licks a giant lollipop bigger than its whole head." },
  h7: { pair: "Hawk + Seventh Sky", emoji: "🦅", scene: "A hawk soars so high it reaches the Seventh Sky and waves down." },
  h8: { pair: "Hartebeest + Ate", emoji: "🦌", scene: "A hartebeest Ate eight bananas for breakfast and fell fast asleep." },
};

const SET7: Record<string, Scene> = {
  a1: { pair: "Aladdin + Sun", emoji: "☀️", scene: "Aladdin rubs his lamp and out pops a genie as bright as the Sun!" },
  a2: { pair: "Aurora + Zoo", emoji: "🌸", scene: "Aurora sleeps so long the Zoo animals tiptoe past her bed." },
  a3: { pair: "Alice + Tree", emoji: "🐇", scene: "Alice tumbles down a hole and lands inside a giant hollow Tree." },
  a4: { pair: "Anna + Door", emoji: "❄️", scene: "Anna knocks on every Door in the castle calling for Elsa!" },
  a5: { pair: "Ariel + Hive", emoji: "🐠", scene: "Ariel pokes an underwater Hive and a hundred bubble-bees zoom out." },
  a6: { pair: "Andersen + Sticks", emoji: "📖", scene: "Andersen the storyteller builds a tiny hut from Sticks and tells tales inside." },
  a7: { pair: "Avalon + Heaven", emoji: "🏰", scene: "Avalon floats so high it tickles the clouds of Heaven every morning." },
  a8: { pair: "Archer + Gate", emoji: "🏹", scene: "The Archer shoots a golden arrow that rings the castle Gate like a bell." },
  b1: { pair: "Beast + Bun", emoji: "🥀", scene: "The Beast gobbles a giant Bun and crumbs fly all over his enchanted castle." },
  b2: { pair: "Belle + Glue", emoji: "📚", scene: "Belle accidentally sits on Glue and her book sticks to her all day." },
  b3: { pair: "Beanstalk + Bee", emoji: "🌱", scene: "A giant Bee lands on the Beanstalk and Jack thinks it is a tiny flying cow." },
  b4: { pair: "Briar + Floor", emoji: "🌹", scene: "Briar roses spread across the Floor so nobody can walk without tiptoeing." },
  b5: { pair: "Bluebeard + Dive", emoji: "🗝️", scene: "Bluebeard does a huge belly Dive into his treasure room and scares the gold coins." },
  b6: { pair: "Brownie + Bricks", emoji: "🧚", scene: "A helpful Brownie lays tiny Bricks to fix the pig's house while everyone sleeps." },
  b7: { pair: "Buckwheat + Eleven", emoji: "🍞", scene: "The magic Buckwheat loaf feeds Eleven hungry dwarfs and still has one slice left." },
  b8: { pair: "Bluebird + Plate", emoji: "🐦", scene: "The enchanted Bluebird delivers a hot Plate of porridge right to Goldilocks." },
  c1: { pair: "Cinderella + Fun", emoji: "👠", scene: "Cinderella has so much Fun at the ball she forgets to watch the clock." },
  c2: { pair: "Cauldron + Stew", emoji: "🪄", scene: "The witch stirs her bubbling Cauldron and out pops a bowl of glittery Stew." },
  c3: { pair: "Castle + Key", emoji: "🏰", scene: "The Castle door needs a tiny golden Key that is hidden inside a frog's hat." },
  c4: { pair: "Charm + Snore", emoji: "✨", scene: "The sleeping Charm is so strong the whole kingdom Snores together in harmony." },
  c5: { pair: "Cupboard + Five", emoji: "🚪", scene: "Behind the magic Cupboard live Five tiny elves who only come out on Tuesdays." },
  c6: { pair: "Crystal + Chicks", emoji: "💎", scene: "The Crystal ball hatches six fluffy Chicks and they peep at the surprised wizard." },
  c7: { pair: "Cobbler + Leaven", emoji: "👞", scene: "The elf Cobbler puts Leaven in his bread so it rises up and lifts the shoes off the shelf." },
  c8: { pair: "Coach + Late", emoji: "🎃", scene: "Cinderella's Coach turns back to a pumpkin and she is very Late for breakfast." },
  d1: { pair: "Dragon + Run", emoji: "🐉", scene: "The Dragon sneezes fire and all the knights Run away with smoking armour." },
  d2: { pair: "Dwarf + Moo", emoji: "⛏️", scene: "A Dwarf finds a magic cow and it goes Moo in a voice that shakes the mountain." },
  d3: { pair: "Donkey + Sea", emoji: "🫏", scene: "Pinocchio's Donkey ears pop out and he swims across the Sea to find Geppetto." },
  d4: { pair: "Duchess + Roar", emoji: "👑", scene: "The Duchess hears a Roar outside and throws pepper at the lion thinking it sneezed." },
  d5: { pair: "Diamond + Drive", emoji: "💎", scene: "The Diamond slipper takes the coach on a magical Drive through the sparkling forest." },
  d6: { pair: "Djinn + Kicks", emoji: "🧞", scene: "The Djinn pops out of the bottle and Kicks the lid so high it lands on the moon." },
  d7: { pair: "Dame + Seven Heads", emoji: "🧙‍♀️", scene: "The wise Dame counts the dragon's Seven Heads and names every single one." },
  d8: { pair: "Dungeon + Crate", emoji: "🗝️", scene: "The princess finds a secret Crate in the Dungeon filled with singing mice." },
  e1: { pair: "Elf + One", emoji: "🧝", scene: "One tiny Elf makes One shoe so perfectly that the cobbler cries happy tears." },
  e2: { pair: "Enchantress + Crew", emoji: "🪄", scene: "The Enchantress turns the whole ship Crew into cheerful singing frogs." },
  e3: { pair: "Emperor + Tea", emoji: "👘", scene: "The Emperor wears invisible clothes and drinks his Tea pretending nothing is wrong." },
  e4: { pair: "Egg + More", emoji: "🥚", scene: "Humpty Dumpty rolls off the wall and cries for More omelette from the king's horses." },
  e5: { pair: "Enchanted Forest + Alive", emoji: "✨", scene: "The Enchanted forest comes Alive and all the trees giggle at the lost knight." },
  e6: { pair: "Evil Queen + Fix", emoji: "🍎", scene: "The Evil Queen tries to Fix her magic mirror but it only tells jokes now." },
  e7: { pair: "Elixir + Heaven", emoji: "⚗️", scene: "One sip of the Elixir sends the little princess floating up toward Heaven like a balloon." },
  e8: { pair: "Eldest Princess + Skate", emoji: "👸", scene: "The Eldest princess puts on her glass shoes and tries to Skate across the frozen moat." },
  f1: { pair: "Fairy + Nun", emoji: "🧚", scene: "The Fairy godmother is so startled by a Nun she turns the broom into a horse." },
  f2: { pair: "Frog Prince + Chew", emoji: "🐸", scene: "The Frog Prince sits on a golden plate and Chews his lily pad very loudly." },
  f3: { pair: "Fox + Flea", emoji: "🦊", scene: "The clever Fox flicks a Flea off his ear and it lands in the witch's cauldron." },
  f4: { pair: "Flask + Store", emoji: "⚗️", scene: "The wizard keeps every spell in a Flask he bought at the magic Store downtown." },
  f5: { pair: "Faun + Jive", emoji: "🐾", scene: "The Faun does a wild Jive dance and his hooves make the forest floor shake." },
  f6: { pair: "Fiend + Tricks", emoji: "👺", scene: "The sneaky Fiend plays Tricks on the three little pigs by gluing their door shut." },
  f7: { pair: "Fountain + Seven Seas", emoji: "⛲", scene: "The wishing Fountain has sailed the Seven Seas and grants wishes smelling of seaweed." },
  f8: { pair: "Fortress + Weight", emoji: "🏰", scene: "The Fortress gate is so heavy even the giant uses all his Weight to push it open." },
  g1: { pair: "Giant + Gun", emoji: "🌩️", scene: "The Giant sneezes so hard it sounds like a Gun and Jack tumbles off the beanstalk." },
  g2: { pair: "Genie + Blue", emoji: "🧞", scene: "The Genie pops out completely Blue and says he ran out of other colours today." },
  g3: { pair: "Gnome + Ski", emoji: "🏔️", scene: "The little Gnome straps mushrooms to his feet and tries to Ski down the enchanted hill." },
  g4: { pair: "Griffin + Pour", emoji: "🦅", scene: "The Griffin tips the rain cloud over to Pour gold coins on the sleeping princess." },
  g5: { pair: "Goblin + Thrive", emoji: "👺", scene: "The Goblin tends his magic garden and all his pumpkins Thrive into giant coaches." },
  g6: { pair: "Gretel + Mix", emoji: "🍭", scene: "Gretel finds the candy house and tries to Mix the chocolate door into a smoothie." },
  g7: { pair: "Godmother + Seven Dwarfs", emoji: "🧚", scene: "The Godmother visits the Seven Dwarfs and turns them all into tiny carriages." },
  g8: { pair: "Gargoyle + Great", emoji: "🗿", scene: "The Gargoyle perches on the Great castle tower and makes silly faces at knights." },
  h1: { pair: "Hansel + Swan", emoji: "🍬", scene: "Hansel rides a friendly Swan because the witch ate all his breadcrumb trail again." },
  h2: { pair: "Hedgehog + Shoe", emoji: "🦔", scene: "The enchanted Hedgehog tries on Cinderella's glass Shoe and gets his snout stuck." },
  h3: { pair: "Hermit + Knee", emoji: "🧙", scene: "The old Hermit wizard bows so low his Knee touches the floor and flowers bloom." },
  h4: { pair: "Hag + Boar", emoji: "🧟", scene: "The wicked Hag turns the prince into a Boar and he snuffles for truffles." },
  h5: { pair: "Horn + Chive", emoji: "🦄", scene: "The unicorn's Horn chops the Chive so fine it sprinkles onto the dragon's soup." },
  h6: { pair: "Herald + Licks", emoji: "📯", scene: "The royal Herald Licks the enchanted trumpet and it plays a tune that wakes the royals." },
  h7: { pair: "Highness + Seventh Sky", emoji: "👑", scene: "Her Highness floats up to the Seventh Sky on a bubble and waves at the stars." },
  h8: { pair: "Huntsman + Ate", emoji: "🪓", scene: "The kind Huntsman baked eight pies and Ate every last one before the wolf arrived." },
};

const SET8: Record<string, Scene> = {
  a1: { pair: "Antman + Sun", emoji: "☀️", scene: "Antman shrinks so tiny he rides a sunbeam like a slide." },
  a2: { pair: "Aquaman + Zoo", emoji: "🐠", scene: "Aquaman talks to every fish at the Zoo and they all wave back." },
  a3: { pair: "Avenger + Tree", emoji: "🌳", scene: "The Avenger lands on a tall Tree and the squirrels cheer." },
  a4: { pair: "Atom + Door", emoji: "⚛️", scene: "Atom shrinks and slips under the Door without turning the handle." },
  a5: { pair: "Archer + Hive", emoji: "🏹", scene: "Archer shoots an arrow and it lands right in the bee Hive — oops!" },
  a6: { pair: "Acrobat-hero + Sticks", emoji: "🤸", scene: "The Acrobat-hero juggles six Sticks while doing a backflip." },
  a7: { pair: "Aqualad + Heaven", emoji: "💧", scene: "Aqualad swims so high he splashes all the clouds in Heaven." },
  a8: { pair: "Atlas + Gate", emoji: "💪", scene: "Atlas holds up the whole Gate with just one pinky finger." },
  b1: { pair: "Batman + Bun", emoji: "🦇", scene: "Batman lands on a giant sticky Bun and gets his cape all gooey." },
  b2: { pair: "Bolt + Glue", emoji: "⚡", scene: "Bolt runs so fast he steps in Glue and zooms away with it stuck to his boot." },
  b3: { pair: "Bee-hero + Bee", emoji: "🐝", scene: "The Bee-hero and a real Bee have a buzzing contest and both win." },
  b4: { pair: "Blizzard + Floor", emoji: "❄️", scene: "Blizzard sneezes and the whole Floor turns into a slippery ice rink." },
  b5: { pair: "Blaster + Dive", emoji: "💥", scene: "Blaster takes a giant Dive into the pool and blasts water everywhere." },
  b6: { pair: "Bumble + Bricks", emoji: "🐝", scene: "Bumble lifts a stack of Bricks with her tiny wings and buzzes off giggling." },
  b7: { pair: "Bolt-boy + Eleven", emoji: "⚡", scene: "Bolt-boy runs around the track Eleven times before breakfast is ready." },
  b8: { pair: "Blaze + Plate", emoji: "🔥", scene: "Blaze melts a Plate into a frisbee and sails it across the sky." },
  c1: { pair: "Cape-hero + Fun", emoji: "🦸", scene: "The Cape-hero's cape blows so wide everyone grabs on for the most Fun ride ever." },
  c2: { pair: "Cyclone + Stew", emoji: "🌪️", scene: "Cyclone spins so fast she stirs a giant pot of Stew without a spoon." },
  c3: { pair: "Comet-hero + Key", emoji: "☄️", scene: "Comet-hero flies through space and uses his blazing tail to jingle a giant Key." },
  c4: { pair: "Crystal-hero + Snore", emoji: "💎", scene: "Crystal turns into a diamond and her Snore makes the whole cave sparkle with rainbows." },
  c5: { pair: "Captain + Five", emoji: "🦸", scene: "Captain holds up Five fingers and five rockets launch at once." },
  c6: { pair: "Cosmo + Chicks", emoji: "🌌", scene: "Cosmo zooms past and a trail of baby Chicks floats behind him in zero gravity." },
  c7: { pair: "Crane-hero + Leaven", emoji: "🦅", scene: "Crane flaps her giant wings so gently the bread dough rises with Leaven by itself." },
  c8: { pair: "Colossal + Late", emoji: "🦣", scene: "Colossal is always Late because one step takes three whole blocks and everyone watches." },
  d1: { pair: "Dash + Run", emoji: "💨", scene: "Dash goes on a Run so fast his shoes smoke and his hair stands straight up." },
  d2: { pair: "Dynamo + Moo", emoji: "⚡", scene: "Dynamo charges up by hugging a cow and the cow goes Moo in total surprise." },
  d3: { pair: "Diver-hero + Sea", emoji: "🤿", scene: "Diver leaps from the clouds all the way down into the shiny blue Sea." },
  d4: { pair: "Dragon-hero + Roar", emoji: "🐉", scene: "Dragon lets out a Roar so loud the whole neighbourhood hears it and claps." },
  d5: { pair: "Dasher + Drive", emoji: "💨", scene: "Dasher hops in the car and goes on the fastest Drive anyone has ever seen." },
  d6: { pair: "Dynakid + Kicks", emoji: "⚡", scene: "Dynakid powers up with a big stretch then sends sparks flying with her Kicks." },
  d7: { pair: "Dazzle + Seven Heads", emoji: "✨", scene: "Dazzle lights up so bright that all Seven Heads of the monster need sunglasses." },
  d8: { pair: "Detector + Crate", emoji: "🔍", scene: "Detector sniffs out every hidden cookie inside the giant wooden Crate." },
  e1: { pair: "Electric + One", emoji: "⚡", scene: "Electric zaps just One lightbulb and the whole city turns on at once." },
  e2: { pair: "Eagle-eye + Crew", emoji: "🦅", scene: "Eagle-eye spots the whole Crew hiding behind a tiny leaf and waves hello." },
  e3: { pair: "Elasto + Tea", emoji: "🤸", scene: "Elasto stretches his arm across the table to pour everyone's Tea without moving." },
  e4: { pair: "Ember + More", emoji: "🔥", scene: "Ember glows so warm everyone wants More marshmallows to toast on her finger." },
  e5: { pair: "Energizer + Alive", emoji: "⚡", scene: "Energizer touches a wilted flower and it jumps Alive, bouncing up and down happily." },
  e6: { pair: "Echo + Fix", emoji: "📣", scene: "Echo shouts FIX IT and the broken robot hears it and fixes itself right away." },
  e7: { pair: "Envoy + Heaven", emoji: "🕊️", scene: "Envoy flies messages all the way up to Heaven and the angels give a big thumbs up." },
  e8: { pair: "Eclipse-hero + Skate", emoji: "🌑", scene: "Eclipse turns off the sun for a second so everyone can Skate in cool shadow." },
  f1: { pair: "Flash + Nun", emoji: "⚡", scene: "Flash zooms past a Nun so fast her habit spins like a top and she laughs." },
  f2: { pair: "Falcon + Chew", emoji: "🦅", scene: "Falcon swoops down, grabs a piece of gum, and Chews all the way to the moon." },
  f3: { pair: "Firefly-hero + Flea", emoji: "✨", scene: "Firefly glows so bright that even the tiny Flea needs little sunglasses." },
  f4: { pair: "Forcefield + Store", emoji: "🛡️", scene: "Forcefield wraps a sparkly bubble around the whole candy Store to keep it safe." },
  f5: { pair: "Flyer + Jive", emoji: "🪂", scene: "Flyer grooves through the sky doing the Jive and loop-the-looping all at once." },
  f6: { pair: "Frostbite + Tricks", emoji: "❄️", scene: "Frostbite sneezes and does ice Tricks, turning every puddle into a skating rink." },
  f7: { pair: "Firestorm + Seven Seas", emoji: "🔥", scene: "Firestorm warms all Seven Seas until every whale pops up to say hello." },
  f8: { pair: "Feather + Weight", emoji: "🪶", scene: "Feather lifts incredible Weight because she is SO light nothing can hold her down." },
  g1: { pair: "Green Lantern + Gun", emoji: "💚", scene: "Green Lantern shapes his ring light into a toy squirt Gun and everyone gets splashed." },
  g2: { pair: "Glider + Blue", emoji: "🪂", scene: "Glider soars through the bright Blue sky waving at every fluffy cloud she passes." },
  g3: { pair: "Glacier + Ski", emoji: "🧊", scene: "Glacier freezes a hill in one breath and then Skis all the way down laughing." },
  g4: { pair: "Gust + Pour", emoji: "💨", scene: "Gust blows so hard she tips the watering can and makes it Pour on the whole garden." },
  g5: { pair: "Galaxy-hero + Thrive", emoji: "🌌", scene: "Galaxy sprinkles stardust and every flower in the garden begins to Thrive and glow." },
  g6: { pair: "Gadgeteer + Mix", emoji: "🔧", scene: "Gadgeteer Mixes six bubbling potions and the robot does a hilarious wiggle dance." },
  g7: { pair: "Guardian + Seven Dwarfs", emoji: "🛡️", scene: "Guardian wraps giant wings around all Seven Dwarfs at once and keeps them cosy." },
  g8: { pair: "Giant-hero + Great", emoji: "🦣", scene: "Giant takes one Great big step and lands three towns away, waving a sheepish sorry." },
  h1: { pair: "Hawk-hero + Swan", emoji: "🦅", scene: "Hawk and a Swan race across the sky and Hawk slows down to let the swan win." },
  h2: { pair: "Hypno + Shoe", emoji: "🌀", scene: "Hypno swings a giant Shoe like a pendulum and everyone falls asleep smiling." },
  h3: { pair: "Hulk + Knee", emoji: "💚", scene: "Hulk bumps his Knee on the coffee table and the whole building shakes with a boom." },
  h4: { pair: "Hammer-hero + Boar", emoji: "🔨", scene: "Hammer hero taps gently to wake a sleeping Boar but the boar just snores louder." },
  h5: { pair: "Hover + Chive", emoji: "🚁", scene: "Hover floats above the garden and uses a Chive stalk as a tiny propeller for fun." },
  h6: { pair: "Hailstorm + Licks", emoji: "🧊", scene: "Hailstorm drops ice cream scoops from the sky and the puppy Licks every single one." },
  h7: { pair: "Highflyer + Seventh Sky", emoji: "✈️", scene: "Highflyer soars all the way to the Seventh Sky and plants a tiny flag up there." },
  h8: { pair: "Hercules + Ate", emoji: "💪", scene: "Hercules Ate so much super-spinach he lifted the whole lunch table into the air." },
};

const SET9: Record<string, Scene> = {
  a1: { pair: "Aladdin + Sun", emoji: "🧞", scene: "Aladdin rubs his lamp and a giant Sun pops out instead of a genie!" },
  a2: { pair: "Anna + Zoo", emoji: "🦁", scene: "Anna from Frozen visits a Zoo and tries to hug every single animal." },
  a3: { pair: "Ariel + Tree", emoji: "🧜", scene: "Ariel the mermaid gets legs and immediately climbs a Tree upside down." },
  a4: { pair: "Astro Boy + Door", emoji: "🤖", scene: "Astro Boy blasts through a Door with his rocket boots and says oops!" },
  a5: { pair: "Anpanman + Hive", emoji: "🍞", scene: "Anpanman feeds his bread face to bees pouring out of a Hive." },
  a6: { pair: "Arnold + Sticks", emoji: "🏈", scene: "Hey Arnold juggles Sticks on his football-shaped head without dropping one." },
  a7: { pair: "Akira + Heaven", emoji: "🏍️", scene: "Akira rides his motorbike so fast he zooms all the way up to Heaven." },
  a8: { pair: "Arthur + Gate", emoji: "🐜", scene: "Arthur the aardvark gets his big glasses stuck in a squeaky old Gate." },
  b1: { pair: "Bambi + Bun", emoji: "🦌", scene: "Bambi slips on ice and lands nose-first in a giant warm Bun." },
  b2: { pair: "Baloo + Glue", emoji: "🐻", scene: "Baloo the bear dances and gets both his big paws stuck in Glue." },
  b3: { pair: "Belle + Bee", emoji: "🌹", scene: "Belle is reading her book when a Bee lands right on her nose." },
  b4: { pair: "Bugs Bunny + Floor", emoji: "🐰", scene: "Bugs Bunny digs a tunnel and pops up through the Floor munching a carrot." },
  b5: { pair: "Bluey + Dive", emoji: "🐕", scene: "Bluey does a belly-flop Dive into a puddle and soaks Dad completely." },
  b6: { pair: "Buzz Lightyear + Bricks", emoji: "🚀", scene: "Buzz Lightyear tries to fly but crash-lands into a wall of Bricks." },
  b7: { pair: "Bob the Builder + Eleven", emoji: "🔨", scene: "Bob the Builder hammers Eleven nails all at once with one giant swing." },
  b8: { pair: "Boo + Plate", emoji: "👧", scene: "Little Boo giggle-smashes her spaghetti Plate on Sully's head." },
  c1: { pair: "Cinderella + Fun", emoji: "👠", scene: "Cinderella loses her glass slipper and has so much Fun sliding in socks." },
  c2: { pair: "Chhota Bheem + Stew", emoji: "💪", scene: "Chhota Bheem eats a whole pot of Stew and flexes his enormous muscles." },
  c3: { pair: "Carl + Key", emoji: "🎈", scene: "Carl from Up ties a Key to a thousand balloons and watches it float away." },
  c4: { pair: "Courage + Snore", emoji: "🐶", scene: "Courage the dog hides under the bed because a monster is doing a loud Snore." },
  c5: { pair: "Coraline + Five", emoji: "🧥", scene: "Coraline buttons up Five coats because the Other World is very very cold." },
  c6: { pair: "Chip + Chicks", emoji: "🐿️", scene: "Chip the chipmunk tries to carry six tiny Chicks on his acorn-stuffed cheeks." },
  c7: { pair: "Chowder + Leaven", emoji: "🍲", scene: "Chowder pours Leaven into his soup and the whole pot bounces off the ceiling." },
  c8: { pair: "Curious George + Late", emoji: "🐒", scene: "Curious George hides the alarm clock and makes the Man in the Yellow Hat very Late." },
  d1: { pair: "Dumbo + Run", emoji: "🐘", scene: "Dumbo flaps his ears so fast he goes for a Run around the whole circus tent." },
  d2: { pair: "Doraemon + Moo", emoji: "🤖", scene: "Doraemon pulls a robot cow from his pocket and it goes Moo right in his ear." },
  d3: { pair: "Dory + Sea", emoji: "🐟", scene: "Dory swims in circles in the Sea because she already forgot which way is home." },
  d4: { pair: "Donald Duck + Roar", emoji: "🦆", scene: "Donald Duck does his biggest Roar but it comes out as a tiny quack." },
  d5: { pair: "Dibo + Drive", emoji: "🐲", scene: "Dibo the gift dragon grants a wish and a tiny car appears for him to Drive." },
  d6: { pair: "Darkwing Duck + Kicks", emoji: "🦸", scene: "Darkwing Duck practices his flying Kicks but trips over his own purple cape." },
  d7: { pair: "Dipper + Seven Heads", emoji: "📓", scene: "Dipper from Gravity Falls draws a monster with Seven Heads in his journal." },
  d8: { pair: "Dash + Crate", emoji: "⚡", scene: "Dash runs so fast he laps a Crate of oranges before anyone blinks." },
  e1: { pair: "Elsa + One", emoji: "❄️", scene: "Elsa builds One giant ice castle with just a single wave of her hand." },
  e2: { pair: "Eeyore + Crew", emoji: "🫏", scene: "Eeyore's tail falls off again and his whole Crew tries to pin it back on." },
  e3: { pair: "Eddy + Tea", emoji: "🍵", scene: "Eddy sells a cup of Tea for twenty-five cents and brags about it all day." },
  e4: { pair: "Elmo + More", emoji: "🔴", scene: "Elmo wants More tickles and giggles so loud the whole street can hear." },
  e5: { pair: "Elastigirl + Alive", emoji: "🦸‍♀️", scene: "Elastigirl stretches so far she springs Alive across three whole rooms at once." },
  e6: { pair: "Ernie + Fix", emoji: "🔧", scene: "Ernie tries to Fix the leaky fence but nails his own boot to it." },
  e7: { pair: "Ewok + Heaven", emoji: "🌟", scene: "Wicket the Ewok thinks the spaceship trail in the sky is the road to Heaven." },
  e8: { pair: "Edd + Skate", emoji: "🛹", scene: "Edd wears a helmet, knee pads and elbow pads just to Skate one centimetre." },
  f1: { pair: "Finn + Nun", emoji: "🗡️", scene: "Finn the Human mistakes a Nun for a villain and tries to bop her with his sword." },
  f2: { pair: "Flounder + Chew", emoji: "🐠", scene: "Flounder the fish tries to Chew seaweed bigger than his whole body." },
  f3: { pair: "Fifi + Flea", emoji: "🌸", scene: "Fifi the Flowertot finds a tiny Flea riding a daisy petal like a surfboard." },
  f4: { pair: "Foxface + Store", emoji: "🦊", scene: "Foxface opens a woodland Store and sells acorns to every animal on the hill." },
  f5: { pair: "Frosty + Jive", emoji: "⛄", scene: "Frosty the Snowman does a wiggly Jive and his carrot nose flies across the yard." },
  f6: { pair: "Fievel + Tricks", emoji: "🐭", scene: "Fievel the mouse pulls cheese Tricks and fools the big cat every single time." },
  f7: { pair: "Flapjack + Seven Seas", emoji: "🍬", scene: "Flapjack sails the Seven Seas looking for the biggest candy island ever made." },
  f8: { pair: "Ferb + Weight", emoji: "🔩", scene: "Ferb builds a machine and lifts twice his own Weight without saying a word." },
  g1: { pair: "Goofy + Gun", emoji: "🎉", scene: "Goofy fires a confetti Gun and gets tangled in streamers head to toe." },
  g2: { pair: "Groot + Blue", emoji: "🌱", scene: "Baby Groot paints himself Blue and dances thinking nobody can see him." },
  g3: { pair: "Gumball + Ski", emoji: "🐱", scene: "Gumball straps tiny Skis on and rolls down a mountain shouting wheeee!" },
  g4: { pair: "Genie + Pour", emoji: "🧞", scene: "Genie Pours a waterfall of wishes and accidentally floods the whole cave." },
  g5: { pair: "Gaston + Thrive", emoji: "💪", scene: "Gaston eats five dozen eggs every morning and says that is why he can Thrive." },
  g6: { pair: "Gerald + Mix", emoji: "🦒", scene: "Gerald the giraffe tries to Mix a smoothie but his long neck tips the blender over." },
  g7: { pair: "Grumpy + Seven Dwarfs", emoji: "😠", scene: "Grumpy argues that all Seven Dwarfs whistle the wrong way while they work." },
  g8: { pair: "Gurgi + Great", emoji: "🐾", scene: "Gurgi says he has done something Great and waves his furry paws proudly." },
  h1: { pair: "Hercules + Swan", emoji: "🦢", scene: "Hercules tries to lift a Swan but it honks and chases him across the river." },
  h2: { pair: "Hiro + Shoe", emoji: "🤖", scene: "Hiro programs Baymax to tie his Shoe but Baymax ties both feet together." },
  h3: { pair: "Heidi + Knee", emoji: "⛰️", scene: "Heidi skips down the mountain and scrapes her Knee on a friendly boulder." },
  h4: { pair: "He-Man + Boar", emoji: "💥", scene: "Cartoon He-Man arm-wrestles a wild Boar and the whole table explodes." },
  h5: { pair: "Handy Manny + Chive", emoji: "🔧", scene: "Handy Manny plants a tiny Chive in his toolbox and it grows right through the lid." },
  h6: { pair: "Hagrid + Licks", emoji: "🧙", scene: "Hagrid's baby dragon Licks his beard and Hagrid giggles like a little kid." },
  h7: { pair: "Huckleberry Hound + Seventh Sky", emoji: "🐶", scene: "Huckleberry Hound howls his off-key song all the way up to the Seventh Sky." },
  h8: { pair: "Horton + Ate", emoji: "🐘", scene: "Horton the elephant Ate the whole clover patch while listening for the Whos." },
};

const SET10: Record<string, Scene> = {
  a1: { pair: "Auto-rickshaw + Sun", emoji: "🛺", scene: "An auto-rickshaw zooms so fast it crashes into the Sun and bounces back giggling." },
  a2: { pair: "Aeroplane + Zoo", emoji: "✈️", scene: "An aeroplane lands inside the Zoo and all the monkeys climb onto the wings." },
  a3: { pair: "Ambulance + Tree", emoji: "🚑", scene: "An ambulance gets stuck up a Tree and honks its siren at a squirrel for help." },
  a4: { pair: "ATV + Door", emoji: "🏍️", scene: "An ATV smashes through a Door and skids across the kitchen tiles." },
  a5: { pair: "Airship + Hive", emoji: "🎈", scene: "An airship floats into a giant Hive and a thousand bees try to fly it away." },
  a6: { pair: "Airboat + Sticks", emoji: "⛵", scene: "An airboat spins through a pile of Sticks and launches them like tiny rockets." },
  a7: { pair: "Astro-rover + Heaven", emoji: "🛸", scene: "An astro-rover rolls all the way up to Heaven and beeps hello at the clouds." },
  a8: { pair: "Antique-car + Gate", emoji: "🚗", scene: "An antique car putters to the Gate, toots a tiny horn, and the gate curtsies open." },
  b1: { pair: "Bulldozer + Bun", emoji: "🚜", scene: "A bulldozer scoops up a giant Bun and wears it on its scoop like a silly hat." },
  b2: { pair: "Bicycle + Glue", emoji: "🚲", scene: "A bicycle rides through Glue and gets its wheels stuck spinning in the air." },
  b3: { pair: "Bus + Bee", emoji: "🚌", scene: "A big yellow bus opens its doors and a thousand bees pour out in tiny seatbelts." },
  b4: { pair: "Blimp + Floor", emoji: "🎈", scene: "A blimp squeezes indoors and bounces along the Floor knocking over the furniture." },
  b5: { pair: "Biplane + Dive", emoji: "✈️", scene: "A biplane does a Dive and the pilot's sandwich flies straight up into the sky." },
  b6: { pair: "Backhoe + Bricks", emoji: "🏗️", scene: "A backhoe scoops up a tower of Bricks and juggles them one by one." },
  b7: { pair: "Buggy + Eleven", emoji: "🏎️", scene: "A dune buggy zooms past Eleven surprised grandmas sitting in a row on their porch." },
  b8: { pair: "Boat + Plate", emoji: "⛵", scene: "A little boat sails into the kitchen and drops a full Plate perfectly on the table." },
  c1: { pair: "Cable-car + Fun", emoji: "🚡", scene: "A cable car full of clowns slides down the wire having so much Fun they forget to stop." },
  c2: { pair: "Crane + Stew", emoji: "🏗️", scene: "A crane lowers its hook into a giant pot of Stew and fishes out a rubber duck." },
  c3: { pair: "Caterpillar-tractor + Key", emoji: "🚜", scene: "A caterpillar tractor rolls over a Key and flattens it into a shiny pancake." },
  c4: { pair: "Cargo-ship + Snore", emoji: "🚢", scene: "A cargo ship sails so slowly the captain falls asleep and his Snore blows the sails open." },
  c5: { pair: "Chopper + Five", emoji: "🚁", scene: "A chopper high-Fives five seagulls with its spinning rotor and they spin away laughing." },
  c6: { pair: "Concrete-mixer + Chicks", emoji: "🌀", scene: "A concrete mixer spins and five fluffy Chicks ride inside it like a merry-go-round." },
  c7: { pair: "Capsule-rocket + Leaven", emoji: "🚀", scene: "A capsule rocket rises with the Leaven of a thousand loaves baked in its engine." },
  c8: { pair: "Camper-van + Late", emoji: "🚐", scene: "A camper van shows up so Late everyone is already in pyjamas and yawning." },
  d1: { pair: "Dragster + Run", emoji: "🏎️", scene: "A dragster's Run is so fast it laps the track before the flag is even dropped." },
  d2: { pair: "Dump-truck + Moo", emoji: "🚛", scene: "A dump truck tips its load and a hundred cows tumble out all going Moo at once." },
  d3: { pair: "Dinghy + Sea", emoji: "⛵", scene: "A tiny dinghy bobs on the Sea with a very serious penguin at the helm." },
  d4: { pair: "Diesel-train + Roar", emoji: "🚂", scene: "A diesel train lets out such a Roar that every pigeon in the city flies away." },
  d5: { pair: "Delivery-drone + Drive", emoji: "🚁", scene: "A delivery drone crash-lands in the Drive and leaves a pizza on the garden gnome." },
  d6: { pair: "Digger + Kicks", emoji: "⛏️", scene: "A digger swings its bucket and Kicks a pile of mud so high it lands on the roof." },
  d7: { pair: "Double-decker + Seven Heads", emoji: "🚌", scene: "A double-decker bus has Seven Heads poking out the top windows in the same funny hat." },
  d8: { pair: "Dune-buggy + Crate", emoji: "🏍️", scene: "A dune buggy smashes through a wooden Crate and tiny rubber ducks rain down." },
  e1: { pair: "Electric-car + One", emoji: "🚗", scene: "An electric car wins by One tiny centimetre and beeps so loud it wakes the moon." },
  e2: { pair: "Excavator + Crew", emoji: "🏗️", scene: "An excavator scoops up a whole Crew of builders and sets them down for a tea break." },
  e3: { pair: "Express-train + Tea", emoji: "🚄", scene: "An express train zooms past so fast it whooshes the Tea out of everyone's cups." },
  e4: { pair: "Engine + More", emoji: "🔧", scene: "A giant Engine keeps asking for More coal and the shovellers keep throwing in more." },
  e5: { pair: "Earthmover + Alive", emoji: "🚜", scene: "An earthmover scoops up mud that turns out to be a surprised and very Alive frog." },
  e6: { pair: "E-scooter + Fix", emoji: "🛴", scene: "An e-scooter breaks down so the robot Fixes it with a banana and it actually works." },
  e7: { pair: "Elevator-pod + Heaven", emoji: "🛗", scene: "An elevator pod shoots up so far it pokes through the clouds and arrives in Heaven." },
  e8: { pair: "Escape-rocket + Skate", emoji: "🚀", scene: "An escape rocket blasts off but first does a perfect figure-eight Skate on the launchpad." },
  f1: { pair: "Fire-engine + Nun", emoji: "🚒", scene: "A fire engine zooms past a surprised Nun and blasts her with a friendly squirt of water." },
  f2: { pair: "Forklift + Chew", emoji: "🏗️", scene: "A forklift picks up a giant piece of bubblegum and the driver starts to Chew it." },
  f3: { pair: "Flying-saucer + Flea", emoji: "🛸", scene: "A flying saucer lands and the only passenger is one tiny Flea in a spacesuit." },
  f4: { pair: "Freight-train + Store", emoji: "🚂", scene: "A freight train crashes through a Store and the tins of beans roll neatly onto the shelves." },
  f5: { pair: "Funicular + Jive", emoji: "🚞", scene: "A funicular rocks left and right doing the Jive all the way up the mountain." },
  f6: { pair: "Formula-one + Tricks", emoji: "🏎️", scene: "A Formula One car does three backflip Tricks and still crosses the finish line first." },
  f7: { pair: "Ferry + Seven Seas", emoji: "⛴️", scene: "A ferry sails the Seven Seas to deliver one letter to an extremely grateful octopus." },
  f8: { pair: "Float-plane + Weight", emoji: "✈️", scene: "A float-plane lands but the Weight of all its snacks makes it sink a little." },
  g1: { pair: "Go-kart + Gun", emoji: "🏎️", scene: "A go-kart shoots out of the starting Gun and zooms around the track in a blink." },
  g2: { pair: "Gondola + Blue", emoji: "🚣", scene: "A gondola glides through bright Blue water and the singer makes the fish jump out." },
  g3: { pair: "Glider + Ski", emoji: "🛩️", scene: "A glider swoops down a snowy Ski slope and waves at every snowman it passes." },
  g4: { pair: "Garbage-truck + Pour", emoji: "🚛", scene: "A garbage truck tips over and banana peels Pour out like a waterfall onto the street." },
  g5: { pair: "Gas-balloon + Thrive", emoji: "🎈", scene: "A gas balloon floats over the city and the flowers Thrive as it rains lemonade." },
  g6: { pair: "Gyrocopter + Mix", emoji: "🚁", scene: "A gyrocopter spins so fast it Mixes all the autumn leaves into a whirlwind." },
  g7: { pair: "Galaxy-ship + Seven Dwarfs", emoji: "🚀", scene: "A galaxy-ship picks up all Seven Dwarfs who argue the whole trip about the window seat." },
  g8: { pair: "Giant-robot + Great", emoji: "🤖", scene: "A giant robot stomps into town and is so Great at carrying everyone's heavy shopping bags." },
  h1: { pair: "Hovercraft + Swan", emoji: "🛥️", scene: "A hovercraft skims the lake and a Swan rides on top looking very pleased with itself." },
  h2: { pair: "Helicopter + Shoe", emoji: "🚁", scene: "A helicopter picks up a giant Shoe and flies it back to the embarrassed giant who lost it." },
  h3: { pair: "Hot-rod + Knee", emoji: "🚗", scene: "A hot rod screeches to a stop and the driver bangs his Knee and does a silly ow dance." },
  h4: { pair: "Harvester + Boar", emoji: "🌾", scene: "A harvester rumbles through the field and wakes a grumpy Boar napping in the wheat." },
  h5: { pair: "Hoverboard + Chive", emoji: "🛹", scene: "A hoverboard zips through the herb garden and comes back smelling entirely of Chive." },
  h6: { pair: "Hydrofoil + Licks", emoji: "🚤", scene: "A hydrofoil skips over the waves so fast a sea lion Licks the hull as it flies past." },
  h7: { pair: "Hypersonic-jet + Seventh Sky", emoji: "✈️", scene: "A hypersonic jet punches through the Seventh Sky and arrives at tomorrow early." },
  h8: { pair: "Horse-carriage + Ate", emoji: "🐴", scene: "A horse-drawn carriage pulls up and the horse Ate all eight cakes before anyone sat down." },
};

export interface Theme { id: string; name: string; emoji: string; blurb: string; scenes: Record<string, Scene>; }

// All themes share the SAME rank-rhyme grid (1=Sun, 2=Shoe, 3=Tree, 4=Door, 5=Hive,
// 6=Sticks, 7=Heaven, 8=Gate). Only the file word changes per theme. Easy keeps the
// file animal constant too (8 animals x 8 objects), so there are only 16 things to learn.
export const THEMES: Theme[] = [
  { id: "easy",  name: "Easy Start",       emoji: "\ud83d\udc23", blurb: "Just 8 animals + 8 objects", scenes: EASY },
  { id: "set1",  name: "Classic Animals",  emoji: "\ud83d\udc1c", blurb: "Everyday animals being silly", scenes: SET1 },
  { id: "set2",  name: "Indian Mythology", emoji: "\ud83d\udd49\ufe0f", blurb: "Gods & heroes of the epics", scenes: SET2 },
  { id: "set3",  name: "Food Chaos",       emoji: "\ud83c\udf69", blurb: "Kitchen & snack silliness", scenes: SET3 },
  { id: "set4",  name: "Space & Aliens",   emoji: "\ud83d\ude80", blurb: "Astronauts, planets, UFOs", scenes: SET4 },
  { id: "set5",  name: "Ocean",            emoji: "\ud83d\udc2c", blurb: "Underwater creatures", scenes: SET5 },
  { id: "set6",  name: "Jungle Safari",    emoji: "\ud83e\udd81", blurb: "Wild jungle animals", scenes: SET6 },
  { id: "set7",  name: "Fairy Tales",      emoji: "\ud83c\udff0", blurb: "Princesses, dragons, magic", scenes: SET7 },
  { id: "set8",  name: "Superheroes",      emoji: "\ud83e\uddb8", blurb: "Heroes & superpowers", scenes: SET8 },
  { id: "set9",  name: "Cartoons",         emoji: "\ud83d\udcfa", blurb: "Beloved cartoon stars", scenes: SET9 },
  { id: "set10", name: "Vehicles",         emoji: "\ud83d\ude97", blurb: "Cars, trains, planes, robots", scenes: SET10 },
];
export const themeById = (id: string): Theme => THEMES.find((t) => t.id === id) ?? THEMES[0]!;
export const DEFAULT_THEME_ID = "easy";

// Back-compat: the original single export still points at Set 1.
export const SCENES: Record<string, Scene> = SET1;

// The two noble armies — every piece is a beloved character (not good vs evil).
export interface PieceChar {
  glyph: string;
  role: string;
  name: string;
  feature: string;
  sound: string;
  /** Identifies WHICH of the pair/set this entry represents:
   *   - Knight: "b" (queen-side, b-file) | "g" (king-side, g-file)
   *   - Bishop: "light" (light-square) | "dark" (dark-square)
   *   - Rook:   "a" (queen-side, a-file) | "h" (king-side, h-file)
   *   - Pawn:   "a" | "b" | "c" | "d" | "e" | "f" | "g" | "h" (starting file)
   *  undefined = combined/generic entry (fallback / gallery-only). */
  variant?: string;
}

export const WHITE_ARMY: PieceChar[] = [
  { glyph: "♔", role: "King",   name: "Little Krishna", feature: "Blue skin, peacock feather, flute", sound: "Flute note 🎵" },
  { glyph: "♕", role: "Queen",  name: "Hanuman",        feature: "Flying monkey-god, golden mace",  sound: "“Jai Shri Ram!”" },
  { glyph: "♘", role: "Knight", name: "Bheem",          feature: "The b-knight — laddoo-loving strongman on his white horse", sound: "“Dhishoom!”", variant: "b" },
  { glyph: "♘", role: "Knight", name: "Chutki",         feature: "The g-knight — pink-dress girl on her white horse", sound: "“Heehee!”", variant: "g" },
  { glyph: "♗", role: "Bishop", name: "Warrior Arjuna", feature: "The dark-square bishop — battle-hardened Arjuna, Gandiva bow", sound: "Bowstring “TWANG!”", variant: "dark" },
  { glyph: "♗", role: "Bishop", name: "Young Arjuna",   feature: "The light-square bishop — young Arjuna, Gandiva bow",    sound: "Arrow whistle",   variant: "light" },
  { glyph: "♖", role: "Rook",   name: "Dholu",  feature: "The a-file (queen-side) rook — riding a white elephant", sound: "“Hehehe!”",  variant: "a" },
  { glyph: "♖", role: "Rook",   name: "Bholu",  feature: "The h-file (king-side) rook — riding a white elephant",   sound: "“Hehehe!”",  variant: "h" },
  { glyph: "♙", role: "Pawn",   name: "8 Minions",      feature: "Yellow, brave; promote into Hanuman!", sound: "“Banana!”" },
];

export const BLACK_ARMY: PieceChar[] = [
  { glyph: "♚", role: "King",   name: "Lord Shiva",    feature: "Trident, crescent moon, meditation pose", sound: "“Om” / temple bell" },
  { glyph: "♛", role: "Queen",  name: "Nandi",         feature: "Sacred bull, golden bells", sound: "“Mooooo” + bells" },
  { glyph: "♞", role: "Knight", name: "Tom",           feature: "The b-knight — sneering cat on his dark horse", sound: "Cat sneer", variant: "b" },
  { glyph: "♞", role: "Knight", name: "Jerry",         feature: "The g-knight — cheeky mouse on his dark horse", sound: "“Eek eek!”", variant: "g" },
  { glyph: "♝", role: "Bishop", name: "Warrior Karna", feature: "The dark-square bishop — battle-hardened Karna, Vijaya bow", sound: "Arrow “FWOOSH!”", variant: "dark" },
  { glyph: "♝", role: "Bishop", name: "Young Karna",   feature: "The light-square bishop — young Karna, Vijaya bow",     sound: "Bowstring “TWANG!”", variant: "light" },
  { glyph: "♜", role: "Rook",   name: "Motu",   feature: "The a-file (queen-side) rook — riding a dark elephant", sound: "“Samosa!”",          variant: "a" },
  { glyph: "♜", role: "Rook",   name: "Patlu",  feature: "The h-file (king-side) rook — riding a dark elephant",   sound: "“Motu, careful!”",  variant: "h" },
  { glyph: "♟", role: "Pawn",   name: "8 Lilliputs",   feature: "Tiny medieval warriors", sound: "Marching “Hup hup hup!”" },
];

export const ALL_SQUARES: string[] = (() => {
  const out: string[] = [];
  for (const f of "abcdefgh") for (let r = 1; r <= 8; r++) out.push(f + r);
  return out;
})();

// Light/dark colour of a square, for styling.
export const isLightSquare = (sq: string): boolean => {
  const file = sq.charCodeAt(0) - 97; // a=0
  const rank = Number(sq[1]) - 1;
  return (file + rank) % 2 === 1;
};
